// src/lib/trophyDefinitions.js
//
// Earned-trophy catalog. These are AUTO-AWARDED milestones — distinct
// from the decorative emoji picker on the profile (that one lets a
// user choose any 5 emojis for display; this one tracks achievements
// they've actually unlocked).
//
// Criteria are checked SERVER-SIDE in grant_eligible_trophies()
// (migrations 167 + 323) so a client can't fake having earned one.
// The catalog here mirrors the server's list — when you change one,
// change the other.
//
// ── LADDERS: why every trophy belongs to one ──────────────────────
//
// A flat list of badges has an end, and the day a user collects the
// last one the feature is over for them. Every trophy here is a RUNG
// on a named ladder instead, and three mechanics guarantee there is
// always a next thing:
//
//   1. Rungs are ordered. Clearing "Consistent" (10 workouts) reveals
//      "Committed" (50) as the live target — the page shows the next
//      rung, not the whole wall.
//   2. Most ladders have an INFINITE TAIL. Past the last named rung,
//      ids are generated by formula — `sessions_x1` is 200 workouts,
//      `sessions_x2` is 300 — and resolved by parseLadderTail() the
//      same way parseSeasonTrophy() resolves league trophies. The
//      catalog stays finite; the ladder does not.
//   3. Some ladders don't exist until you're in the feature at all
//      (crew wars, gauntlet, prestige), so the board grows sideways
//      as well as upward.
//
// A few ladders deliberately DEAD-END, and that is a design decision
// rather than an oversight — see `tailBase: null` and the note on
// each. Anything that would reward training longer, further or more
// often without limit is a ladder we should not build.
//
// TAIL IDS ARE NOT IN `TROPHIES`, for the same reason league season
// trophies aren't: TROPHIES.length is the "12 / 40 earned" denominator
// on the profile, and a denominator that grows forever would make
// every collection look permanently unfinished.

import { enT as asIs } from '@/lib/translatorArg';

export const TROPHY_TIERS = {
  bronze:    { label: 'Bronze',    color: '#cd7f32', order: 1 },
  silver:    { label: 'Silver',    color: '#c0c0c0', order: 2 },
  gold:      { label: 'Gold',      color: '#ffd700', order: 3 },
  platinum:  { label: 'Platinum',  color: '#7be0e0', order: 4 },
  legendary: { label: 'Legendary', color: '#a855f7', order: 5 },
};

// ── Ladder metadata ───────────────────────────────────────────────
//
// Each entry:
//   name      what the ladder is called on the page
//   category  which group it sits in
//   signal    key in the payload from get_trophy_progress() that this
//             ladder measures against — this is the contract with the
//             server, so renaming one means editing migration 323 too
//   unit      suffix for the progress readout ("47 / 100 workouts")
//   tailBase  threshold of the LAST named rung. null = no tail (the
//             ladder ends on purpose; the comment says why)
//   tailStep  how much further each tail rung costs
//   tailName  the top rung's name, which tails extend with numerals
//             ("Centurion" → "Centurion II", "Centurion III", …)
//   tailCap   safety limit on generated rungs (see parseLadderTail)
export const LADDERS = {
  sessions:  { name: 'Sessions',        category: 'workout',    signal: 'workouts',        unit: 'workouts', tailBase: 100,     tailStep: 100,     tailName: 'Centurion' },
  tonnage:   { name: 'Tonnage',         category: 'workout',    signal: 'volumeLbs',       unit: 'lb',       tailBase: 1000000, tailStep: 1000000, tailName: 'Millionaire' },
  variety:   { name: 'Variety',         category: 'workout',    signal: 'distinctLifts',   unit: 'lifts',    tailBase: 100,     tailStep: 50,      tailName: 'Completionist' },

  streak:    { name: 'Streak',          category: 'streak',     signal: 'workoutStreak',   unit: 'days',     tailBase: 365,     tailStep: 365,     tailName: 'Eternal Flame' },
  longevity: { name: 'Longevity',       category: 'streak',     signal: 'activeMonths',    unit: 'months',   tailBase: 24,      tailStep: 12,      tailName: 'Veteran' },
  quests:    { name: 'Quests',          category: 'streak',     signal: 'questsClaimed',   unit: 'quests',   tailBase: 500,     tailStep: 500,     tailName: 'Quest Machine' },
  perfect:   { name: 'Perfect days',    category: 'streak',     signal: 'perfectDays',     unit: 'days',     tailBase: 100,     tailStep: 100,     tailName: 'Flawless Hundred' },

  // DEAD END BY DESIGN. The rungs are real race distances people train
  // for; past a marathon the next "rung" is an ultra, and a badge is
  // not a reason to attempt one. Lifetime distance carries the endless
  // half of this category instead.
  cardio:    { name: 'Distance PB',     category: 'cardio',     signal: 'maxDistanceM',    unit: 'm',        tailBase: null },
  distance:  { name: 'Lifetime miles',  category: 'cardio',     signal: 'totalDistanceM',  unit: 'm',        tailBase: 1000000, tailStep: 1000000, tailName: 'Four Digits' },
  // DEAD END BY DESIGN — there is a finite number of activity types.
  cross:     { name: 'Cross training',   category: 'cardio',     signal: 'activityTypes',   unit: 'types',    tailBase: null },

  // DEAD END BY DESIGN — level 100 is the cap; prestige is the tail.
  level:     { name: 'Level',           category: 'level',      signal: 'level',           unit: '',         tailBase: null },
  prestige:  { name: 'Prestige',        category: 'level',      signal: 'prestige',        unit: '',         tailBase: 5,       tailStep: 1,       tailName: 'Eternal Return' },
  goals:     { name: 'Goals',           category: 'level',      signal: 'goalsDone',       unit: 'goals',    tailBase: 50,      tailStep: 50,      tailName: 'Relentless' },

  duel:      { name: 'Duels',           category: 'duel',       signal: 'duelWins',        unit: 'wins',     tailBase: 200,     tailStep: 200,     tailName: 'Immortal' },
  bounty:    { name: 'Bounties',        category: 'duel',       signal: 'bountiesClaimed', unit: 'bounties', tailBase: 50,      tailStep: 50,      tailName: 'Most Wanted' },
  // DEAD END BY DESIGN — the gauntlet path is a fixed course.
  gauntlet:  { name: 'Gauntlet',        category: 'duel',       signal: 'gauntletDone',    unit: '',         tailBase: null },

  // DEAD END BY DESIGN — you are either in a crew or you are not.
  crew:      { name: 'Crew',            category: 'crew',       signal: 'crewCount',       unit: '',         tailBase: null },
  crewwar:   { name: 'Crew wars',       category: 'crew',       signal: 'crewWars',        unit: 'wars',     tailBase: 50,      tailStep: 50,      tailName: 'Warlord' },

  social:    { name: 'Hub',             category: 'social',     signal: 'posts',           unit: 'posts',    tailBase: 200,     tailStep: 200,     tailName: 'Hub Legend' },
  gym:       { name: 'Gym visits',      category: 'social',     signal: 'checkins',        unit: 'visits',   tailBase: 365,     tailStep: 365,     tailName: 'Institution' },

  capsule:   { name: 'Capsules',        category: 'collection', signal: 'capsulesOpened',  unit: 'capsules', tailBase: 100,     tailStep: 100,     tailName: 'Vault Keeper' },
  relic:     { name: 'Legendaries',     category: 'collection', signal: 'legendaries',     unit: 'items',    tailBase: 25,      tailStep: 25,      tailName: 'Mythic Vault' },
  coins:     { name: 'Coins earned',    category: 'collection', signal: 'coinsEarned',     unit: 'coins',    tailBase: 100000,  tailStep: 100000,  tailName: 'Tycoon' },
  market:    { name: 'Marketplace',     category: 'collection', signal: 'marketSales',     unit: 'sales',    tailBase: 50,      tailStep: 50,      tailName: 'Merchant' },

  // Nutrition had NO ladder at all until now, which was a real gap: the
  // retired achievements catalog carried six nutrition badges and the
  // trophy engine replaced them with nothing.
  meals:     { name: 'Meals logged',    category: 'nutrition',  signal: 'meals',           unit: 'meals',    tailBase: 1000,    tailStep: 1000,    tailName: 'Meal Prepper' },
  ndays:     { name: 'Days logged',     category: 'nutrition',  signal: 'nutritionDays',   unit: 'days',     tailBase: 365,     tailStep: 365,     tailName: 'Year of Logging' },

  sleep:     { name: 'Sleep',           category: 'recovery',   signal: 'sleepLogs',       unit: 'nights',   tailBase: 100,     tailStep: 100,     tailName: 'Recovery Focused' },
  journal:   { name: 'Journal',         category: 'recovery',   signal: 'journalEntries',  unit: 'entries',  tailBase: 50,      tailStep: 50,      tailName: 'Chronicler' },
  debrief:   { name: 'Weekly reviews',  category: 'recovery',   signal: 'debriefs',        unit: 'weeks',    tailBase: 52,      tailStep: 52,      tailName: 'Year Reviewed' },

  regimen:   { name: 'Programming',     category: 'workout',    signal: 'regimens',        unit: 'regimens', tailBase: 25,      tailStep: 25,      tailName: 'Program Director' },
  duelplay:  { name: 'Duels fought',    category: 'duel',       signal: 'duelsPlayed',     unit: 'duels',    tailBase: 100,     tailStep: 100,     tailName: 'Veteran of the Pit' },
  comments:  { name: 'Comments',        category: 'social',     signal: 'comments',        unit: 'comments', tailBase: 100,     tailStep: 100,     tailName: 'Pillar of the Hub' },
  followers: { name: 'Followers',       category: 'social',     signal: 'followers',       unit: 'followers', tailBase: 200,    tailStep: 200,     tailName: 'Figurehead' },
};

// Group labels for the page, in display order.
export const TROPHY_CATEGORIES = [
  { id: 'workout',    name: 'Iron',        emoji: '🏋️' },
  { id: 'streak',     name: 'Consistency', emoji: '🔥' },
  { id: 'cardio',     name: 'Endurance',   emoji: '🏃' },
  { id: 'nutrition',  name: 'Fuel',        emoji: '🥗' },
  { id: 'recovery',   name: 'Recovery',    emoji: '🌙' },
  { id: 'level',      name: 'Progression', emoji: '⚡' },
  { id: 'duel',       name: 'Arena',       emoji: '⚔️' },
  { id: 'crew',       name: 'Crew',        emoji: '🛡️' },
  { id: 'social',     name: 'Community',   emoji: '💬' },
  { id: 'collection', name: 'Collection',  emoji: '🎁' },
];

// Each entry:
//   id          unique trophy id (must match migration 323's VALUES list)
//   name        display name
//   description criteria copy ("Log your 100th workout")
//   emoji       trophy art
//   tier        bronze | silver | gold | platinum | legendary
//   category    workout | streak | level | duel | crew | cardio | social | collection
//   ladder      key in LADDERS — which ladder this is a rung on
//   threshold   the signal value that earns it (drives the progress bar)
export const TROPHIES = [
  // ── Iron · sessions ─────────────────────────────────────────────
  { id: 'first_rep',       category: 'workout', ladder: 'sessions',  threshold: 1,       tier: 'bronze',    emoji: '🥉', name: 'First Rep',         description: 'Logged your first workout.' },
  { id: 'consistent',      category: 'workout', ladder: 'sessions',  threshold: 10,      tier: 'silver',    emoji: '🥈', name: 'Consistent',        description: '10 workouts logged.' },
  { id: 'committed',       category: 'workout', ladder: 'sessions',  threshold: 50,      tier: 'gold',      emoji: '🥇', name: 'Committed',         description: '50 workouts logged.' },
  { id: 'centurion',       category: 'workout', ladder: 'sessions',  threshold: 100,     tier: 'platinum',  emoji: '🏆', name: 'Centurion',         description: '100 workouts logged.' },

  // ── Iron · tonnage ──────────────────────────────────────────────
  // Thresholds are in POUNDS of lifetime volume. The old (dead)
  // achievements catalog had "one_ton_lifted" at target 1000 with no
  // unit anywhere — a ton is 2,000 lb, and being wrong about that is
  // how you ship a badge that means nothing.
  { id: 'tonnage_ton',     category: 'workout', ladder: 'tonnage',   threshold: 2000,    tier: 'bronze',    emoji: '🏋️', name: 'One Ton',           description: 'Moved 2,000 lb of lifetime volume.' },
  { id: 'tonnage_10t',     category: 'workout', ladder: 'tonnage',   threshold: 20000,   tier: 'silver',    emoji: '🏗️', name: 'Ten Ton',           description: 'Moved 20,000 lb of lifetime volume.' },
  { id: 'tonnage_100t',    category: 'workout', ladder: 'tonnage',   threshold: 200000,  tier: 'gold',      emoji: '🏛️', name: 'Hundred Ton',       description: 'Moved 200,000 lb of lifetime volume.' },
  { id: 'tonnage_million', category: 'workout', ladder: 'tonnage',   threshold: 1000000, tier: 'platinum',  emoji: '💎', name: 'Millionaire',       description: 'Moved 1,000,000 lb of lifetime volume.' },

  // ── Iron · variety ──────────────────────────────────────────────
  { id: 'variety_10',      category: 'workout', ladder: 'variety',   threshold: 10,      tier: 'bronze',    emoji: '🎽', name: 'Generalist',        description: 'Logged 10 different exercises.' },
  { id: 'variety_25',      category: 'workout', ladder: 'variety',   threshold: 25,      tier: 'silver',    emoji: '🎯', name: 'Well Rounded',      description: 'Logged 25 different exercises.' },
  { id: 'variety_50',      category: 'workout', ladder: 'variety',   threshold: 50,      tier: 'gold',      emoji: '📖', name: 'Encyclopedia',      description: 'Logged 50 different exercises.' },
  { id: 'variety_100',     category: 'workout', ladder: 'variety',   threshold: 100,     tier: 'platinum',  emoji: '🧭', name: 'Completionist',     description: 'Logged 100 different exercises.' },

  // ── Consistency · streak ────────────────────────────────────────
  { id: 'streak_spark',    category: 'streak',  ladder: 'streak',    threshold: 7,       tier: 'bronze',    emoji: '🔥', name: 'Spark',             description: 'Workout streak of 7 days.' },
  { id: 'streak_blaze',    category: 'streak',  ladder: 'streak',    threshold: 30,      tier: 'silver',    emoji: '🔥', name: 'Blaze',             description: 'Workout streak of 30 days.' },
  { id: 'streak_inferno',  category: 'streak',  ladder: 'streak',    threshold: 100,     tier: 'gold',      emoji: '🔥', name: 'Inferno',           description: 'Workout streak of 100 days.' },
  { id: 'streak_eternal',  category: 'streak',  ladder: 'streak',    threshold: 365,     tier: 'legendary', emoji: '🔥', name: 'Eternal Flame',     description: 'Workout streak of 365 days.' },

  // ── Consistency · longevity ─────────────────────────────────────
  // Months in which you logged at least one workout. Deliberately the
  // one ladder nobody can rush: it only moves with the calendar.
  { id: 'longevity_3',     category: 'streak',  ladder: 'longevity', threshold: 3,       tier: 'bronze',    emoji: '🌙', name: 'Three Moons',       description: 'Trained in 3 separate months.' },
  { id: 'longevity_6',     category: 'streak',  ladder: 'longevity', threshold: 6,       tier: 'silver',    emoji: '🗓️', name: 'Half Year',         description: 'Trained in 6 separate months.' },
  { id: 'longevity_12',    category: 'streak',  ladder: 'longevity', threshold: 12,      tier: 'gold',      emoji: '🎂', name: 'Anniversary',       description: 'Trained in 12 separate months.' },
  { id: 'longevity_24',    category: 'streak',  ladder: 'longevity', threshold: 24,      tier: 'platinum',  emoji: '🎖️', name: 'Veteran',           description: 'Trained in 24 separate months.' },

  // ── Consistency · quests ────────────────────────────────────────
  { id: 'quest_10',        category: 'streak',  ladder: 'quests',    threshold: 10,      tier: 'bronze',    emoji: '✅', name: 'Errand Runner',     description: 'Claimed 10 daily quests.' },
  { id: 'quest_100',       category: 'streak',  ladder: 'quests',    threshold: 100,     tier: 'silver',    emoji: '📋', name: 'Taskmaster',        description: 'Claimed 100 daily quests.' },
  { id: 'quest_500',       category: 'streak',  ladder: 'quests',    threshold: 500,     tier: 'gold',      emoji: '⚙️', name: 'Quest Machine',     description: 'Claimed 500 daily quests.' },

  { id: 'perfect_7',       category: 'streak',  ladder: 'perfect',   threshold: 7,       tier: 'bronze',    emoji: '💯', name: 'Perfect Week',      description: '7 days with every quest cleared.' },
  { id: 'perfect_30',      category: 'streak',  ladder: 'perfect',   threshold: 30,      tier: 'silver',    emoji: '🌟', name: 'Perfect Month',     description: '30 days with every quest cleared.' },
  { id: 'perfect_100',     category: 'streak',  ladder: 'perfect',   threshold: 100,     tier: 'gold',      emoji: '✨', name: 'Flawless Hundred',  description: '100 days with every quest cleared.' },

  // ── Endurance · single-session distance ─────────────────────────
  { id: 'cardio_5k',       category: 'cardio',  ladder: 'cardio',    threshold: 5000,    tier: 'bronze',    emoji: '🏃', name: '5K Club',           description: 'Logged a 5K+ cardio session.' },
  { id: 'cardio_10k',      category: 'cardio',  ladder: 'cardio',    threshold: 10000,   tier: 'silver',    emoji: '🏃', name: '10K Club',          description: 'Logged a 10K+ cardio session.' },
  // 21,097 m, not 21,100 — that is the official half-marathon distance
  // and the number migration 167 already grants on. A mismatch here
  // would show "21,098 / 21,100" on a badge the server already gave you.
  { id: 'cardio_half',     category: 'cardio',  ladder: 'cardio',    threshold: 21097,   tier: 'gold',      emoji: '🏆', name: 'Half Marathoner',   description: 'Logged a 21.1K+ cardio session.' },
  { id: 'cardio_marathon', category: 'cardio',  ladder: 'cardio',    threshold: 42195,   tier: 'legendary', emoji: '🏅', name: 'Marathoner',        description: 'Logged a full 42.2K cardio session.' },

  // ── Endurance · lifetime distance ───────────────────────────────
  { id: 'distance_50k',    category: 'cardio',  ladder: 'distance',  threshold: 50000,   tier: 'bronze',    emoji: '🥾', name: 'Getting Going',     description: '50 km of lifetime cardio distance.' },
  { id: 'distance_250k',   category: 'cardio',  ladder: 'distance',  threshold: 250000,  tier: 'silver',    emoji: '🛣️', name: 'Long Hauler',       description: '250 km of lifetime cardio distance.' },
  { id: 'distance_1000k',  category: 'cardio',  ladder: 'distance',  threshold: 1000000, tier: 'gold',      emoji: '🌍', name: 'Four Digits',       description: '1,000 km of lifetime cardio distance.' },

  // ── Endurance · cross-training ──────────────────────────────────
  { id: 'cross_3',         category: 'cardio',  ladder: 'cross',     threshold: 3,       tier: 'bronze',    emoji: '🔀', name: 'Mixed Bag',         description: 'Logged 3 different cardio activities.' },
  { id: 'cross_5',         category: 'cardio',  ladder: 'cross',     threshold: 5,       tier: 'silver',    emoji: '🤸', name: 'Cross Trainer',     description: 'Logged 5 different cardio activities.' },
  { id: 'cross_8',         category: 'cardio',  ladder: 'cross',     threshold: 8,       tier: 'gold',      emoji: '🃏', name: 'Jack of All',       description: 'Logged 8 different cardio activities.' },

  // ── Progression · level ─────────────────────────────────────────
  { id: 'level_tier1',     category: 'level',   ladder: 'level',     threshold: 10,      tier: 'bronze',    emoji: '⚡', name: 'Tier 1',            description: 'Reached Level 10.' },
  { id: 'level_tier2',     category: 'level',   ladder: 'level',     threshold: 25,      tier: 'silver',    emoji: '⚡', name: 'Tier 2',            description: 'Reached Level 25.' },
  { id: 'level_tier3',     category: 'level',   ladder: 'level',     threshold: 50,      tier: 'gold',      emoji: '⚡', name: 'Tier 3',            description: 'Reached Level 50.' },
  { id: 'level_apex',      category: 'level',   ladder: 'level',     threshold: 100,     tier: 'legendary', emoji: '⚡', name: 'Apex',              description: 'Reached Level 100.' },

  // ── Progression · prestige ──────────────────────────────────────
  { id: 'prestige_1',      category: 'level',   ladder: 'prestige',  threshold: 1,       tier: 'gold',      emoji: '🔄', name: 'Reborn',            description: 'Prestiged once.' },
  { id: 'prestige_3',      category: 'level',   ladder: 'prestige',  threshold: 3,       tier: 'platinum',  emoji: '⚒️', name: 'Thrice Forged',     description: 'Prestiged 3 times.' },
  { id: 'prestige_5',      category: 'level',   ladder: 'prestige',  threshold: 5,       tier: 'legendary', emoji: '♾️', name: 'Eternal Return',    description: 'Prestiged 5 times.' },

  // ── Progression · goals ─────────────────────────────────────────
  { id: 'goal_first',      category: 'level',   ladder: 'goals',     threshold: 1,       tier: 'bronze',    emoji: '🎯', name: 'First Target',      description: 'Completed your first goal.' },
  { id: 'goal_10',         category: 'level',   ladder: 'goals',     threshold: 10,      tier: 'silver',    emoji: '🏹', name: 'Goal Getter',       description: 'Completed 10 goals.' },
  { id: 'goal_50',         category: 'level',   ladder: 'goals',     threshold: 50,      tier: 'gold',      emoji: '🔱', name: 'Relentless',        description: 'Completed 50 goals.' },

  // ── Arena · duels ───────────────────────────────────────────────
  { id: 'duel_challenger', category: 'duel',    ladder: 'duel',      threshold: 1,       tier: 'bronze',    emoji: '⚔️', name: 'Challenger',        description: 'Won your first duel.' },
  { id: 'duel_champion',   category: 'duel',    ladder: 'duel',      threshold: 10,      tier: 'silver',    emoji: '⚔️', name: 'Champion',          description: 'Won 10 duels.' },
  { id: 'duel_gladiator',  category: 'duel',    ladder: 'duel',      threshold: 50,      tier: 'gold',      emoji: '🗡️', name: 'Gladiator',         description: 'Won 50 duels.' },
  { id: 'duel_immortal',   category: 'duel',    ladder: 'duel',      threshold: 200,     tier: 'platinum',  emoji: '👑', name: 'Immortal',          description: 'Won 200 duels.' },

  // ── Arena · bounties ────────────────────────────────────────────
  { id: 'bounty_1',        category: 'duel',    ladder: 'bounty',    threshold: 1,       tier: 'bronze',    emoji: '🎯', name: 'Bounty Hunter',     description: 'Claimed your first bounty.' },
  { id: 'bounty_10',       category: 'duel',    ladder: 'bounty',    threshold: 10,      tier: 'silver',    emoji: '💰', name: 'Collector',         description: 'Claimed 10 bounties.' },
  { id: 'bounty_50',       category: 'duel',    ladder: 'bounty',    threshold: 50,      tier: 'gold',      emoji: '🤠', name: 'Most Wanted',       description: 'Claimed 50 bounties.' },

  // ── Arena · gauntlet ────────────────────────────────────────────
  // `binary` marks a rung that is a yes/no rather than a count, so the
  // page renders a state instead of an "x / y" bar. Without it this one
  // would read "5 / 999", which is not a thing anyone is 5/999 of.
  { id: 'gauntlet_5',      category: 'duel',    ladder: 'gauntlet',  threshold: 5,       tier: 'bronze',    emoji: '🧗', name: 'Gauntlet Runner',   description: 'Cleared 5 gauntlet challenges.' },
  { id: 'gauntlet_path',   category: 'duel',    ladder: 'gauntlet',  threshold: 1, binary: true, signal: 'gauntletPath', tier: 'gold', emoji: '🏔️', name: 'Gauntlet Cleared',  description: 'Completed the full gauntlet path.' },

  // ── Crew ────────────────────────────────────────────────────────
  { id: 'crew_squad',      category: 'crew',    ladder: 'crew',      threshold: 1,       tier: 'bronze',    emoji: '🛡️', name: 'Squad Member',      description: 'Joined your first crew.' },
  // The one non-capstone gate, and it is causal rather than arbitrary:
  // you cannot contribute to a crew war without being in a crew, so
  // anyone who qualifies for this necessarily already holds crew_squad.
  { id: 'crewwar_1',       category: 'crew',    ladder: 'crewwar',   threshold: 1,       tier: 'bronze',    emoji: '🚩', name: 'Enlisted',          description: 'Contributed to your first crew war.',
    requires: ['crew_squad'] },
  { id: 'crewwar_10',      category: 'crew',    ladder: 'crewwar',   threshold: 10,      tier: 'silver',    emoji: '⚔️', name: 'War Veteran',       description: 'Contributed to 10 crew wars.' },
  { id: 'crewwar_50',      category: 'crew',    ladder: 'crewwar',   threshold: 50,      tier: 'gold',      emoji: '🏰', name: 'Warlord',           description: 'Contributed to 50 crew wars.' },

  // ── Community · hub ─────────────────────────────────────────────
  { id: 'post_1',          category: 'social',  ladder: 'social',    threshold: 1,       tier: 'bronze',    emoji: '💬', name: 'First Post',        description: 'Posted to the Hub.' },
  { id: 'post_10',         category: 'social',  ladder: 'social',    threshold: 10,      tier: 'silver',    emoji: '📣', name: 'Regular',           description: '10 Hub posts.' },
  { id: 'post_50',         category: 'social',  ladder: 'social',    threshold: 50,      tier: 'gold',      emoji: '📢', name: 'Voice of the Hub',  description: '50 Hub posts.' },
  { id: 'post_200',        category: 'social',  ladder: 'social',    threshold: 200,     tier: 'platinum',  emoji: '🎙️', name: 'Hub Legend',        description: '200 Hub posts.' },

  // ── Community · gym check-ins ───────────────────────────────────
  { id: 'checkin_1',       category: 'social',  ladder: 'gym',       threshold: 1,       tier: 'bronze',    emoji: '📍', name: 'Showed Up',         description: 'Checked in at a gym.' },
  { id: 'checkin_25',      category: 'social',  ladder: 'gym',       threshold: 25,      tier: 'silver',    emoji: '🏋️‍♀️', name: 'Local',             description: '25 gym visits.' },
  { id: 'checkin_100',     category: 'social',  ladder: 'gym',       threshold: 100,     tier: 'gold',      emoji: '🏛️', name: 'Regular Fixture',   description: '100 gym visits.' },
  { id: 'checkin_365',     category: 'social',  ladder: 'gym',       threshold: 365,     tier: 'platinum',  emoji: '🗿', name: 'Institution',       description: '365 gym visits.' },

  // ── Collection ──────────────────────────────────────────────────
  { id: 'capsule_1',       category: 'collection', ladder: 'capsule', threshold: 1,      tier: 'bronze',    emoji: '🎁', name: 'First Drop',        description: 'Opened your first capsule.' },
  { id: 'capsule_25',      category: 'collection', ladder: 'capsule', threshold: 25,     tier: 'silver',    emoji: '📦', name: 'Hoarder',           description: 'Opened 25 capsules.' },
  { id: 'capsule_100',     category: 'collection', ladder: 'capsule', threshold: 100,    tier: 'gold',      emoji: '🔐', name: 'Vault Keeper',      description: 'Opened 100 capsules.' },

  { id: 'relic_1',         category: 'collection', ladder: 'relic',   threshold: 1,      tier: 'gold',      emoji: '🌟', name: 'Legendary Find',    description: 'Owned your first legendary item.' },
  { id: 'relic_5',         category: 'collection', ladder: 'relic',   threshold: 5,      tier: 'platinum',  emoji: '💫', name: 'Legend Collector',  description: 'Owned 5 legendary items.' },
  { id: 'relic_25',        category: 'collection', ladder: 'relic',   threshold: 25,     tier: 'legendary', emoji: '🔮', name: 'Mythic Vault',      description: 'Owned 25 legendary items.' },

  // ── Collection · coins & marketplace ────────────────────────────
  { id: 'coin_1k',         category: 'collection', ladder: 'coins',   threshold: 1000,   tier: 'bronze',    emoji: '🪙', name: 'Pocket Change',     description: 'Earned 1,000 Flex Coins.' },
  { id: 'coin_10k',        category: 'collection', ladder: 'coins',   threshold: 10000,  tier: 'silver',    emoji: '💰', name: 'Saver',             description: 'Earned 10,000 Flex Coins.' },
  { id: 'coin_100k',       category: 'collection', ladder: 'coins',   threshold: 100000, tier: 'gold',      emoji: '🏦', name: 'Tycoon',            description: 'Earned 100,000 Flex Coins.' },

  { id: 'market_1',        category: 'collection', ladder: 'market',  threshold: 1,      tier: 'bronze',    emoji: '🏷️', name: 'First Sale',        description: 'Sold an item on the marketplace.' },
  { id: 'market_10',       category: 'collection', ladder: 'market',  threshold: 10,     tier: 'silver',    emoji: '🤝', name: 'Trader',            description: 'Sold 10 items.' },
  { id: 'market_50',       category: 'collection', ladder: 'market',  threshold: 50,     tier: 'gold',      emoji: '🏪', name: 'Merchant',          description: 'Sold 50 items.' },

  // ── Fuel · meals ────────────────────────────────────────────────
  { id: 'meal_1',          category: 'nutrition',  ladder: 'meals',   threshold: 1,      tier: 'bronze',    emoji: '🥗', name: 'First Plate',       description: 'Logged your first meal.' },
  { id: 'meal_50',         category: 'nutrition',  ladder: 'meals',   threshold: 50,     tier: 'silver',    emoji: '🍽️', name: 'Tracker',           description: 'Logged 50 meals.' },
  { id: 'meal_250',        category: 'nutrition',  ladder: 'meals',   threshold: 250,    tier: 'gold',      emoji: '📊', name: 'Macro Aware',       description: 'Logged 250 meals.' },
  { id: 'meal_1000',       category: 'nutrition',  ladder: 'meals',   threshold: 1000,   tier: 'platinum',  emoji: '👨‍🍳', name: 'Meal Prepper',      description: 'Logged 1,000 meals.' },

  // ── Fuel · days logged ──────────────────────────────────────────
  { id: 'nday_7',          category: 'nutrition',  ladder: 'ndays',   threshold: 7,      tier: 'bronze',    emoji: '📆', name: 'First Week',        description: 'Logged food on 7 separate days.' },
  { id: 'nday_30',         category: 'nutrition',  ladder: 'ndays',   threshold: 30,     tier: 'silver',    emoji: '🗓️', name: 'Full Month',        description: 'Logged food on 30 separate days.' },
  { id: 'nday_100',        category: 'nutrition',  ladder: 'ndays',   threshold: 100,    tier: 'gold',      emoji: '💯', name: 'Hundred Days',      description: 'Logged food on 100 separate days.' },
  { id: 'nday_365',        category: 'nutrition',  ladder: 'ndays',   threshold: 365,    tier: 'platinum',  emoji: '🎊', name: 'Year of Logging',   description: 'Logged food on 365 separate days.' },

  // ── Recovery ────────────────────────────────────────────────────
  { id: 'sleep_7',         category: 'recovery',   ladder: 'sleep',   threshold: 7,      tier: 'bronze',    emoji: '😴', name: 'Rested',            description: 'Logged 7 nights of sleep.' },
  { id: 'sleep_30',        category: 'recovery',   ladder: 'sleep',   threshold: 30,     tier: 'silver',    emoji: '🌙', name: 'Sleep Tracker',     description: 'Logged 30 nights of sleep.' },
  { id: 'sleep_100',       category: 'recovery',   ladder: 'sleep',   threshold: 100,    tier: 'gold',      emoji: '🛌', name: 'Recovery Focused',  description: 'Logged 100 nights of sleep.' },

  { id: 'journal_1',       category: 'recovery',   ladder: 'journal', threshold: 1,      tier: 'bronze',    emoji: '📓', name: 'Dear Diary',        description: 'Wrote your first journal entry.' },
  { id: 'journal_10',      category: 'recovery',   ladder: 'journal', threshold: 10,     tier: 'silver',    emoji: '✍️', name: 'Reflective',        description: 'Wrote 10 journal entries.' },
  { id: 'journal_50',      category: 'recovery',   ladder: 'journal', threshold: 50,     tier: 'gold',      emoji: '📚', name: 'Chronicler',        description: 'Wrote 50 journal entries.' },

  { id: 'debrief_1',       category: 'recovery',   ladder: 'debrief', threshold: 1,      tier: 'bronze',    emoji: '📈', name: 'Week in Review',    description: 'Received your first weekly review.' },
  { id: 'debrief_10',      category: 'recovery',   ladder: 'debrief', threshold: 10,     tier: 'silver',    emoji: '📉', name: 'Ten Weeks',         description: 'Received 10 weekly reviews.' },
  { id: 'debrief_52',      category: 'recovery',   ladder: 'debrief', threshold: 52,     tier: 'gold',      emoji: '🗂️', name: 'Year Reviewed',     description: 'Received 52 weekly reviews.' },

  // ── Iron · programming ──────────────────────────────────────────
  // Names carried over from the retired achievements catalog so the
  // copy people may already have seen survives the migration.
  { id: 'regimen_1',       category: 'workout',    ladder: 'regimen', threshold: 1,      tier: 'bronze',    emoji: '🏗️', name: 'Regimen Builder',   description: 'Created your first workout regimen.' },
  { id: 'regimen_5',       category: 'workout',    ladder: 'regimen', threshold: 5,      tier: 'silver',    emoji: '📚', name: 'Playlist Master',   description: 'Created 5 different regimens.' },
  { id: 'regimen_10',      category: 'workout',    ladder: 'regimen', threshold: 10,     tier: 'gold',      emoji: '🏢', name: 'Regimen Architect', description: 'Created 10 different regimens.' },
  { id: 'regimen_25',      category: 'workout',    ladder: 'regimen', threshold: 25,     tier: 'platinum',  emoji: '🏛️', name: 'Program Director',  description: 'Created 25 different regimens.' },

  // ── Arena · duels fought ────────────────────────────────────────
  // Separate from duels WON on purpose: a ladder that only rewards
  // winning punishes the person who needs the encouragement most.
  { id: 'duelplay_1',      category: 'duel',       ladder: 'duelplay', threshold: 1,     tier: 'bronze',    emoji: '🤝', name: 'Stepped Up',        description: 'Fought your first duel.' },
  { id: 'duelplay_25',     category: 'duel',       ladder: 'duelplay', threshold: 25,    tier: 'silver',    emoji: '🥊', name: 'Regular Contender', description: 'Fought 25 duels.' },
  { id: 'duelplay_100',    category: 'duel',       ladder: 'duelplay', threshold: 100,   tier: 'gold',      emoji: '🏟️', name: 'Veteran of the Pit', description: 'Fought 100 duels.' },

  // ── Community · comments & followers ────────────────────────────
  { id: 'comment_1',       category: 'social',     ladder: 'comments', threshold: 1,     tier: 'bronze',    emoji: '💭', name: 'Chimed In',         description: 'Left your first comment.' },
  { id: 'comment_25',      category: 'social',     ladder: 'comments', threshold: 25,    tier: 'silver',    emoji: '🗣️', name: 'Conversationalist', description: 'Left 25 comments.' },
  { id: 'comment_100',     category: 'social',     ladder: 'comments', threshold: 100,   tier: 'gold',      emoji: '🏛️', name: 'Pillar of the Hub', description: 'Left 100 comments.' },

  { id: 'follower_1',      category: 'social',     ladder: 'followers', threshold: 1,    tier: 'bronze',    emoji: '👋', name: 'First Follower',    description: 'Someone followed you.' },
  { id: 'follower_10',     category: 'social',     ladder: 'followers', threshold: 10,   tier: 'silver',    emoji: '👥', name: 'Getting Known',     description: '10 followers.' },
  { id: 'follower_50',     category: 'social',     ladder: 'followers', threshold: 50,   tier: 'gold',      emoji: '📣', name: 'Influencer',        description: '50 followers.' },
  { id: 'follower_200',    category: 'social',     ladder: 'followers', threshold: 200,  tier: 'platinum',  emoji: '👑', name: 'Figurehead',        description: '200 followers.' },

  // ── MASTERY · the capstones ─────────────────────────────────────
  //
  // These are the reason the prerequisite engine exists. A capstone has
  // NO numeric criterion of its own — it is earned purely by owning the
  // trophies named in `requires`, which are the top rungs of a whole
  // category. Until then it is LOCKED: it does not appear in a ladder,
  // it is not offered under Next up, and the server will not grant it.
  //
  // Every prerequisite here is strictly implied by the capstone itself,
  // which is the rule for adding any new gate: never require something
  // a qualifying user might not have. A gate that CAN be missed is a
  // permanently unearnable badge, and there is no way to tell the two
  // apart from the outside.
  { id: 'capstone_iron',       category: 'capstone', capstone: true, tier: 'legendary', emoji: '⚒️', name: 'Iron Master',      description: 'Topped every Iron ladder.',
    requires: ['centurion', 'tonnage_million', 'variety_100', 'regimen_25'] },
  { id: 'capstone_consistency', category: 'capstone', capstone: true, tier: 'legendary', emoji: '🔗', name: 'Unbreakable',     description: 'Topped every Consistency ladder.',
    requires: ['streak_eternal', 'longevity_24', 'quest_500', 'perfect_100'] },
  { id: 'capstone_endurance',  category: 'capstone', capstone: true, tier: 'legendary', emoji: '🫁', name: 'Ironlung',         description: 'Topped every Endurance ladder.',
    requires: ['cardio_marathon', 'distance_1000k', 'cross_8'] },
  { id: 'capstone_nutrition',  category: 'capstone', capstone: true, tier: 'legendary', emoji: '🍎', name: 'Fully Fuelled',    description: 'Topped every Fuel ladder.',
    requires: ['meal_1000', 'nday_365'] },
  { id: 'capstone_recovery',   category: 'capstone', capstone: true, tier: 'legendary', emoji: '🌿', name: 'Well Recovered',   description: 'Topped every Recovery ladder.',
    requires: ['sleep_100', 'journal_50', 'debrief_52'] },
  { id: 'capstone_progression', category: 'capstone', capstone: true, tier: 'legendary', emoji: '🌠', name: 'Ascended',        description: 'Topped every Progression ladder.',
    requires: ['level_apex', 'prestige_5', 'goal_50'] },
  { id: 'capstone_arena',      category: 'capstone', capstone: true, tier: 'legendary', emoji: '🏆', name: 'Undisputed',       description: 'Topped every Arena ladder.',
    requires: ['duel_immortal', 'duelplay_100', 'bounty_50', 'gauntlet_path'] },
  { id: 'capstone_community',  category: 'capstone', capstone: true, tier: 'legendary', emoji: '🧱', name: 'Cornerstone',      description: 'Topped every Crew and Community ladder.',
    requires: ['crewwar_50', 'post_200', 'comment_100', 'follower_200', 'checkin_365'] },
  { id: 'capstone_collection', category: 'capstone', capstone: true, tier: 'legendary', emoji: '🗝️', name: 'Curator',          description: 'Topped every Collection ladder.',
    requires: ['capsule_100', 'relic_25', 'coin_100k', 'market_50'] },

  // The only two-level chain in the catalog: it requires the other
  // nine capstones, each of which requires its own ladder tops. That is
  // what the grant engine's fixpoint loop exists for — one call has to
  // resolve the whole chain, or this would need two visits to unlock.
  { id: 'capstone_apex',       category: 'capstone', capstone: true, tier: 'legendary', emoji: '♾️', name: 'Flexyn Complete',  description: 'Earned every other capstone.',
    requires: ['capstone_iron', 'capstone_consistency', 'capstone_endurance', 'capstone_nutrition',
               'capstone_recovery', 'capstone_progression', 'capstone_arena', 'capstone_community',
               'capstone_collection'] },
];

export const TROPHY_BY_ID = Object.fromEntries(TROPHIES.map(t => [t.id, t]));

// ── League season trophies ────────────────────────────────────────────────
//
// These cannot live in TROPHIES, because a new one is minted every 28 days
// and a static catalog would need editing on every roll. They are resolved
// from the id instead: `league_s{n}_{tier}` and `league_s{n}_champion`, both
// written by award_league_season_internal (migration 312).
//
// `TROPHIES.length` is the denominator for the "12 / 40 earned" counter on
// the profile, so season trophies are deliberately NOT added to it — an
// unreachable denominator that grows forever would make the collection look
// permanently unfinished.

const SEASON_TROPHY_RE = /^league_s(\d+)_(bronze|silver|gold|platinum|diamond|legend|champion)$/;

// TROPHY_TIERS has no `diamond` step, so diamond borrows platinum's ramp and
// both legend and champion take `legendary`.
const SEASON_TIER_MAP = {
  bronze: 'bronze', silver: 'silver', gold: 'gold',
  platinum: 'platinum', diamond: 'platinum',
  legend: 'legendary', champion: 'legendary',
};

const SEASON_EMOJI = {
  bronze: '🥉', silver: '🥈', gold: '🥇',
  platinum: '💠', diamond: '💎', legend: '👑', champion: '👑',
};

/** "diamond" → "Diamond". The English label for a season's tier band. */
function seasonKindLabel(kind) {
  return String(kind || '').charAt(0).toUpperCase() + String(kind || '').slice(1);
}

/** Parsed season trophy, or null if `id` isn't one. */
export function parseSeasonTrophy(id) {
  const m = SEASON_TROPHY_RE.exec(id || '');
  if (!m) return null;
  const season = Number(m[1]);
  const kind = m[2];
  const isChampion = kind === 'champion';
  const label = seasonKindLabel(kind);
  return {
    id,
    season,
    kind,
    isChampion,
    category: 'league',
    tier: SEASON_TIER_MAP[kind] || 'bronze',
    emoji: SEASON_EMOJI[kind] || '🎖️',
    // The league tier this trophy marks, so trophy surfaces can draw the
    // tier's own icon (LeagueTierIcon) instead of the emoji. The emoji
    // stays for text-only places such as a shared achievement post.
    leagueTier: isChampion ? 'legend' : kind,
    name: isChampion ? `Champion, S${season}` : `Season ${season} ${label}`,
    description: isChampion
      ? `Won season ${season} outright. Minted once, and nobody else can earn it.`
      : `Reached ${label} in season ${season}.`,
  };
}

// ── Infinite ladder tails ─────────────────────────────────────────
//
// Past the last named rung, ids are generated rather than enumerated:
// `sessions_x1` is 200 workouts, `sessions_x2` is 300, and so on. Same
// trick as the league season trophies above, for the same reason — the
// alternative is a catalog that has to be edited every time somebody
// out-trains it.
//
// Tail rung k requires `tailBase + k * tailStep` and displays as the
// top rung's name in Roman numerals: k=1 → "Centurion II".
//
// Like season trophies, these are NOT in TROPHIES — see the header.

const TAIL_RE = /^([a-z]+)_x(\d+)$/;

// A cap on generated rungs, mirrored in migration 323. Nobody is
// legitimately 50 tail-rungs deep, so a number past this means corrupt
// data rather than a very dedicated user, and it stops one bad
// `total_volume_lbs` from minting thousands of rows.
export const TAIL_CAP = 50;

const ROMAN = [
  [1000, 'M'], [900, 'CM'], [500, 'D'], [400, 'CD'], [100, 'C'], [90, 'XC'],
  [50, 'L'], [40, 'XL'], [10, 'X'], [9, 'IX'], [5, 'V'], [4, 'IV'], [1, 'I'],
];

/** 4 → "IV". Used for tail rung numerals. */
export function toRoman(n) {
  let out = '';
  let rest = Math.max(0, Math.floor(n));
  for (const [value, numeral] of ROMAN) {
    while (rest >= value) { out += numeral; rest -= value; }
  }
  return out;
}

/** Parsed tail trophy, or null if `id` isn't one. */
export function parseLadderTail(id) {
  const m = TAIL_RE.exec(id || '');
  if (!m) return null;
  const ladderId = m[1];
  const k = Number(m[2]);
  const ladder = LADDERS[ladderId];
  // A tail on a ladder that has none is not a trophy — it's a typo or a
  // forged id. Resolve it to null so it renders as nothing rather than
  // as a plausible-looking badge.
  if (!ladder || ladder.tailBase == null || k < 1 || k > TAIL_CAP) return null;

  const threshold = ladder.tailBase + k * ladder.tailStep;
  // Tails sit above the top named rung, so they take the top tier of
  // the ramp. There is nowhere further to escalate.
  return {
    id,
    ladder: ladderId,
    category: ladder.category,
    tier: 'legendary',
    emoji: '♾️',
    threshold,
    isTail: true,
    name: `${ladder.tailName} ${toRoman(k + 1)}`,
    description: `${threshold.toLocaleString()} ${ladder.unit}`.trim(),
  };
}

// ── XP milestones ─────────────────────────────────────────────────────
//
// Five badges granted at total-XP thresholds, each carrying a bonus XP
// payout. They are granted by `grant_xp_milestone_achievements()`
// (migration 341), NOT by `grant_eligible_trophies()` — the trophy engine
// awards no XP, so routing these through it would hand out the badge and
// silently drop the bonus.
//
// They live OUT of `TROPHIES` for the same two reasons league season
// trophies do, and the second one is the load-bearing one:
//
//   1. `TROPHIES.length` is the "12 / 120" denominator. Milestones nobody
//      can work toward on a ladder would make the collection read as
//      permanently unfinished.
//   2. `TROPHIES` is diffed against `grant_eligible_trophies`' named
//      VALUES list, which must stay exact in both directions — a
//      server-granted id missing from the client is silently dropped from
//      the Earned tab. These are granted by a different function, so
//      adding them to the catalog would break that check for no reason.
//
// They still resolve through `getTrophy`, so the Earned tab, the crew
// "First to Achieve" row and a shared Hub post all render them by name.
// Before migration 341 they lived in the retired `public.achievements`
// table and had no client definition at all, so they rendered as nothing.
const XP_MILESTONES = {
  xp_250:   { threshold: 250,   xp: 10,  tier: 'bronze',    emoji: '🔰', name: 'First Steps',     description: 'Earned your first 250 XP.' },
  xp_1000:  { threshold: 1000,  xp: 25,  tier: 'silver',    emoji: '📶', name: 'Getting Serious', description: 'Earned 1,000 XP total.' },
  xp_5000:  { threshold: 5000,  xp: 50,  tier: 'gold',      emoji: '🏵️', name: 'Dedicated',       description: 'Earned 5,000 XP total.' },
  xp_10000: { threshold: 10000, xp: 100, tier: 'platinum',  emoji: '🎗️', name: 'Elite Athlete',   description: 'Earned 10,000 XP total.' },
  xp_25000: { threshold: 25000, xp: 200, tier: 'legendary', emoji: '👑', name: 'Legend',          description: 'Earned 25,000 XP total.' },
};

/** Parsed XP-milestone trophy, or null if `id` isn't one. */
export function parseXpMilestone(id) {
  const m = XP_MILESTONES[id];
  if (!m) return null;
  return { id, category: 'level', isXpMilestone: true, ...m };
}

/** The five milestone ids, ascending. Exported so the suite can diff
 *  them against the migration's thresholds rather than retyping them. */
export const XP_MILESTONE_IDS = Object.keys(XP_MILESTONES)
  .sort((a, b) => XP_MILESTONES[a].threshold - XP_MILESTONES[b].threshold);

export function getTrophy(id) {
  return TROPHY_BY_ID[id]
    || parseSeasonTrophy(id)
    || parseLadderTail(id)
    || parseXpMilestone(id)
    || null;
}

// ── "What's next" ─────────────────────────────────────────────────
//
// The whole point of the ladder structure: given where someone is on a
// ladder, hand back the ONE rung they're working toward. The page shows
// this rather than the full wall, so finishing a rung immediately
// replaces it with the next one instead of leaving a gap.
//
// Returns null only for a ladder that has genuinely ended — the
// deliberate dead ends (see LADDERS). Everything else always answers.
const RUNGS_BY_LADDER = TROPHIES.reduce((acc, t) => {
  if (!t.ladder) return acc;
  (acc[t.ladder] ||= []).push(t);
  return acc;
}, {});
// Order by TIER first, then threshold.
//
// Threshold alone was the order until 2026-08-11, and on 30 of the 31
// ladders the two agree exactly — every rung is measured by the same
// signal, so a bigger number is always a harder rung. `gauntlet` is the
// exception and it inverted: `gauntlet_path` ("complete the whole
// path", GOLD) carries threshold 1 because it is measured against
// `gauntletPath`, while `gauntlet_5` ("clear 5 challenges", BRONZE)
// carries 5 against `gauntletDone`. Sorting two different signals on
// one number ranked the gold rung below the bronze one, so a brand-new
// user was offered "Gauntlet Cleared" as the next thing to go and do.
//
// Tier is the property that actually means "how hard is this", so it
// leads. Thresholds still break ties, which is what keeps the other 30
// ladders byte-identical to the old order.
export function rungSignal(trophy) {
  return trophy?.signal || LADDERS[trophy?.ladder]?.signal || null;
}

Object.values(RUNGS_BY_LADDER).forEach(list => list.sort((a, b) => {
  const d = (TROPHY_TIERS[a.tier]?.order || 0) - (TROPHY_TIERS[b.tier]?.order || 0);
  return d !== 0 ? d : a.threshold - b.threshold;
}));

/** Every named rung on a ladder, easiest tier first. */
export function rungsFor(ladderId) {
  return RUNGS_BY_LADDER[ladderId] || [];
}

/**
 * The next rung on `ladderId` for someone whose ladder signal reads
 * `value`. Falls through the named rungs, then into the generated tail.
 *
 * `progress` is the full signal map from get_trophy_progress(). It is
 * optional only so existing single-signal callers keep working: a rung
 * carrying its own `signal` (today just `gauntlet_path`) is measured
 * against THAT key, because the ladder's signal answers a different
 * question and would report the rung as cleared on the wrong evidence.
 */
export function nextRung(ladderId, value = 0, progress = null) {
  const ladder = LADDERS[ladderId];
  if (!ladder) return null;

  const valueFor = (rung) => {
    const own = rung.signal;
    if (!own || !progress) return value;
    return Number(progress[own]) || 0;
  };

  const named = rungsFor(ladderId).find(r => valueFor(r) < r.threshold);
  if (named) return named;

  // Past every named rung — walk into the tail.
  if (ladder.tailBase == null) return null;
  const k = Math.floor((value - ladder.tailBase) / ladder.tailStep) + 1;
  return parseLadderTail(`${ladderId}_x${Math.min(Math.max(k, 1), TAIL_CAP)}`);
}

// ── Prerequisites ─────────────────────────────────────────────────
//
// A trophy carrying `requires: [id, …]` is LOCKED until every one of
// those is earned. Locked means genuinely unobtainable, not merely
// hidden: migration 324 refuses to grant it even when the numeric
// threshold is met, so the gate cannot be walked around by hitting the
// number first. The page keeps locked entries out of the ladders and
// out of Next up, and counts them in the Locked row instead.
//
// Adding a new gate has one rule, and it is not a style preference:
// **never require something a qualifying user might not have.** A gate
// that can be missed produces a permanently unearnable badge, and from
// the outside that is indistinguishable from a bug. Every gate here is
// strictly implied by the thing it gates.

/** Capstones — earned purely by prerequisite, with no numeric criterion. */
export const CAPSTONES = TROPHIES.filter(t => t.capstone);

/** True when every prerequisite of `trophy` is in `earnedIds`. */
export function isUnlocked(trophy, earnedIds) {
  const reqs = trophy?.requires;
  if (!reqs || !reqs.length) return true;
  const owned = earnedIds instanceof Set ? earnedIds : new Set(earnedIds || []);
  return reqs.every(id => owned.has(id));
}

/** The prerequisites of `trophy`, each resolved and marked done / not. */
export function requirementsFor(trophy, earnedIds) {
  const owned = earnedIds instanceof Set ? earnedIds : new Set(earnedIds || []);
  return (trophy?.requires || []).map(id => {
    const req = getTrophy(id);
    return { id, name: req?.name || id, emoji: req?.emoji || '🔒', done: owned.has(id) };
  });
}

/**
 * Everything still locked for this user: not earned, and with at least
 * one prerequisite outstanding. This is what the Locked row counts.
 */
export function lockedTrophies(earnedIds) {
  const owned = earnedIds instanceof Set ? earnedIds : new Set(earnedIds || []);
  return TROPHIES.filter(t => !owned.has(t.id) && !isUnlocked(t, owned));
}

/**
 * Progress toward `trophy` given the caller's signal value, as
 * { value, target, pct, done }. `pct` is clamped to 0–100.
 */
export function rungProgress(trophy, value = 0) {
  const target = trophy?.threshold || 0;
  const done = target > 0 && value >= target;
  const pct = target > 0 ? Math.min(100, Math.max(0, (value / target) * 100)) : 0;
  return { value, target, pct, done };
}

// ── Translation ───────────────────────────────────────────────────
//
// This module is pure data with no React context, so the translator
// comes IN as an argument — the same shape `implementTypeLabel(slug, tf)`
// uses in equipmentCatalog.js. Every English string stays where it is
// and is passed as the fallback, so a locale with no catalog entry
// renders exactly what it rendered before.
//
// TROPHY NAMES ARE DELIBERATELY NOT ROUTED THROUGH THIS. "Centurion",
// "Eternal Flame" and "Ironlung" are product names, the same class as
// capsule cosmetics and the crew trophies — `_glossary.json` records the
// decision. What a badge is CALLED stays English; what it took to earn
// it is ordinary copy and translates.
//
// Season and tail rungs are generated, so their English is a template
// literal. That shape cannot go in a catalog as-is — it would ship a
// key with no fixed string behind it — so they take the interpolated
// form, `tf(key, 'Reached {tier} in season {n}.', { tier, n })`.

// The default translator lives in src/lib/translatorArg.js. It used to be a
// local `(_key, english) => english`, which dropped the interpolation vars
// and rendered `Champion, S{n}` for every season champion once the trophy
// catalog was extracted. `asIs` is kept as a named alias because
// data/trophies.js imports it.
export { asIs };

/** "Bronze" / "Silver" / … for a tier ramp id. */
export function tierLabel(tier, tf = asIs) {
  const id = TROPHY_TIERS[tier] ? tier : 'bronze';
  return tf(`trophy.tier.${id}`, TROPHY_TIERS[id].label);
}

/** The ladder's display name — the row heading on the trophy board. */
export function ladderName(ladderId, tf = asIs) {
  const ladder = LADDERS[ladderId];
  return ladder ? tf(`trophy.ladder.${ladderId}`, ladder.name) : '';
}

/**
 * The unit suffix on a ladder's "47 / 100 workouts" readout. Keyed by the
 * UNIT rather than by the ladder, because eight ladders count days and a
 * translator should be asked for that word once. Empty for the ladders
 * that count nothing nameable (level, prestige, gauntlet, crew).
 */
export function ladderUnit(ladderId, tf = asIs) {
  const unit = LADDERS[ladderId]?.unit;
  if (!unit) return '';
  return tf(`trophy.unit.${unit}`, unit);
}

/** A category heading — "Iron", "Consistency", "Endurance". */
export function trophyCategoryName(category, tf = asIs) {
  const cat = typeof category === 'string'
    ? TROPHY_CATEGORIES.find((c) => c.id === category)
    : category;
  return cat ? tf(`trophy.category.${cat.id}`, cat.name) : '';
}

/**
 * The criteria line under a trophy. Handles all four kinds `getTrophy`
 * can return: catalog rungs key off their id, season and tail rungs off
 * their shape.
 */
export function trophyDescription(trophy, tf = asIs) {
  if (!trophy) return '';

  if (trophy.season != null && trophy.kind) {
    return trophy.isChampion
      ? tf(
        'trophy.season.champion.desc',
        'Won season {n} outright. Minted once, and nobody else can earn it.',
        { n: trophy.season },
      )
      : tf('trophy.season.tier.desc', 'Reached {tier} in season {n}.', {
        tier: tf(`trophy.seasonTier.${trophy.kind}`, seasonKindLabel(trophy.kind)),
        n: trophy.season,
      });
  }

  if (trophy.isTail) {
    // The English is "200,000 lb" — a formatted number and a unit, which
    // is the whole string. Word order moves between languages, so it is
    // one message with two placeholders rather than a concatenation.
    const threshold = Number(trophy.threshold) || 0;
    return tf('trophy.tail.desc', '{n} {unit}', {
      n: threshold.toLocaleString(),
      unit: ladderUnit(trophy.ladder, tf),
    }).trim();
  }

  return tf(`trophy.${trophy.id}.desc`, trophy.description || '');
}

/** The display name for a trophy. Only the generated season rungs move. */
export function trophyName(trophy, tf = asIs) {
  if (!trophy) return '';
  if (trophy.season != null && trophy.kind) {
    return trophy.isChampion
      ? tf('trophy.season.champion.name', 'Champion, S{n}', { n: trophy.season })
      : tf('trophy.season.tier.name', 'Season {n} {tier}', {
        n: trophy.season,
        tier: tf(`trophy.seasonTier.${trophy.kind}`, seasonKindLabel(trophy.kind)),
      });
  }
  return trophy.name || '';
}
