// src/lib/trophyDefinitions.js
//
// Earned-trophy catalog. These are AUTO-AWARDED milestones — distinct
// from the decorative emoji picker on the profile (that one lets a
// user choose any 5 emojis for display; this one tracks achievements
// they've actually unlocked).
//
// Criteria are checked SERVER-SIDE in grant_eligible_trophies()
// (migrations 167 + 323) so a client can't fake having earned one.
// The catalog here mirrors the server's list — when you change one,
// change the other.
//
// ── LADDERS: why every trophy belongs to one ──────────────────────
//
// A flat list of badges has an end, and the day a user collects the
// last one the feature is over for them. Every trophy here is a RUNG
// on a named ladder instead, and three mechanics guarantee there is
// always a next thing:
//
//   1. Rungs are ordered. Clearing "Consistent" (10 workouts) reveals
//      "Committed" (50) as the live target — the page shows the next
//      rung, not the whole wall.
//   2. Most ladders have an INFINITE TAIL. Past the last named rung,
//      ids are generated by formula — `sessions_x1` is 200 workouts,
//      `sessions_x2` is 300 — and resolved by parseLadderTail() the
//      same way parseSeasonTrophy() resolves league trophies. The
//      catalog stays finite; the ladder does not.
//   3. Some ladders don't exist until you're in the feature at all
//      (crew wars, gauntlet, prestige), so the board grows sideways
//      as well as upward.
//
// A few ladders deliberately DEAD-END, and that is a design decision
// rather than an oversight — see `tailBase: null` and the note on
// each. Anything that would reward training longer, further or more
// often without limit is a ladder we should not build.
//
// TAIL IDS ARE NOT IN `TROPHIES`, for the same reason league season
// trophies aren't: TROPHIES.length is the "12 / 40 earned" denominator
// on the profile, and a denominator that grows forever would make
// every collection look permanently unfinished.

export const TROPHY_TIERS = {
  bronze:    { label: 'Bronze',    color: '#cd7f32', order: 1 },
  silver:    { label: 'Silver',    color: '#c0c0c0', order: 2 },
  gold:      { label: 'Gold',      color: '#ffd700', order: 3 },
  platinum:  { label: 'Platinum',  color: '#7be0e0', order: 4 },
  legendary: { label: 'Legendary', color: '#a855f7', order: 5 },
};

// ── Ladder metadata ───────────────────────────────────────────────
//
// Each entry:
//   name      what the ladder is called on the page
//   category  which group it sits in
//   signal    key in the payload from get_trophy_progress() that this
//             ladder measures against — this is the contract with the
//             server, so renaming one means editing migration 323 too
//   unit      suffix for the progress readout ("47 / 100 workouts")
//   tailBase  threshold of the LAST named rung. null = no tail (the
//             ladder ends on purpose; the comment says why)
//   tailStep  how much further each tail rung costs
//   tailName  the top rung's name, which tails extend with numerals
//             ("Centurion" → "Centurion II", "Centurion III", …)
//   tailCap   safety limit on generated rungs (see parseLadderTail)
export const LADDERS = {
  sessions:  { name: 'Sessions',        category: 'workout',    signal: 'workouts',        unit: 'workouts', tailBase: 100,     tailStep: 100,     tailName: 'Centurion' },
  tonnage:   { name: 'Tonnage',         category: 'workout',    signal: 'volumeLbs',       unit: 'lb',       tailBase: 1000000, tailStep: 1000000, tailName: 'Millionaire' },
  variety:   { name: 'Variety',         category: 'workout',    signal: 'distinctLifts',   unit: 'lifts',    tailBase: 100,     tailStep: 50,      tailName: 'Completionist' },

  streak:    { name: 'Streak',          category: 'streak',     signal: 'workoutStreak',   unit: 'days',     tailBase: 365,     tailStep: 365,     tailName: 'Eternal Flame' },
  longevity: { name: 'Longevity',       category: 'streak',     signal: 'activeMonths',    unit: 'months',   tailBase: 24,      tailStep: 12,      tailName: 'Veteran' },
  quests:    { name: 'Quests',          category: 'streak',     signal: 'questsClaimed',   unit: 'quests',   tailBase: 500,     tailStep: 500,     tailName: 'Quest Machine' },
  perfect:   { name: 'Perfect days',    category: 'streak',     signal: 'perfectDays',     unit: 'days',     tailBase: 100,     tailStep: 100,     tailName: 'Flawless Hundred' },

  // DEAD END BY DESIGN. The rungs are real race distances people train
  // for; past a marathon the next "rung" is an ultra, and a badge is
  // not a reason to attempt one. Lifetime distance carries the endless
  // half of this category instead.
  cardio:    { name: 'Distance PB',     category: 'cardio',     signal: 'maxDistanceM',    unit: 'm',        tailBase: null },
  distance:  { name: 'Lifetime miles',  category: 'cardio',     signal: 'totalDistanceM',  unit: 'm',        tailBase: 1000000, tailStep: 1000000, tailName: 'Four Digits' },
  // DEAD END BY DESIGN — there is a finite number of activity types.
  cross:     { name: 'Cross-training',  category: 'cardio',     signal: 'activityTypes',   unit: 'types',    tailBase: null },

  // DEAD END BY DESIGN — level 100 is the cap; prestige is the tail.
  level:     { name: 'Level',           category: 'level',      signal: 'level',           unit: '',         tailBase: null },
  prestige:  { name: 'Prestige',        category: 'level',      signal: 'prestige',        unit: '',         tailBase: 5,       tailStep: 1,       tailName: 'Eternal Return' },
  goals:     { name: 'Goals',           category: 'level',      signal: 'goalsDone',       unit: 'goals',    tailBase: 50,      tailStep: 50,      tailName: 'Relentless' },

  duel:      { name: 'Duels',           category: 'duel',       signal: 'duelWins',        unit: 'wins',     tailBase: 200,     tailStep: 200,     tailName: 'Immortal' },
  bounty:    { name: 'Bounties',        category: 'duel',       signal: 'bountiesClaimed', unit: 'bounties', tailBase: 50,      tailStep: 50,      tailName: 'Most Wanted' },
  // DEAD END BY DESIGN — the gauntlet path is a fixed course.
  gauntlet:  { name: 'Gauntlet',        category: 'duel',       signal: 'gauntletDone',    unit: '',         tailBase: null },

  // DEAD END BY DESIGN — you are either in a crew or you are not.
  crew:      { name: 'Crew',            category: 'crew',       signal: 'crewCount',       unit: '',         tailBase: null },
  crewwar:   { name: 'Crew wars',       category: 'crew',       signal: 'crewWars',        unit: 'wars',     tailBase: 50,      tailStep: 50,      tailName: 'Warlord' },

  social:    { name: 'Hub',             category: 'social',     signal: 'posts',           unit: 'posts',    tailBase: 200,     tailStep: 200,     tailName: 'Hub Legend' },
  gym:       { name: 'Check-ins',       category: 'social',     signal: 'checkins',        unit: 'visits',   tailBase: 365,     tailStep: 365,     tailName: 'Institution' },

  capsule:   { name: 'Capsules',        category: 'collection', signal: 'capsulesOpened',  unit: 'capsules', tailBase: 100,     tailStep: 100,     tailName: 'Vault Keeper' },
  relic:     { name: 'Legendaries',     category: 'collection', signal: 'legendaries',     unit: 'items',    tailBase: 25,      tailStep: 25,      tailName: 'Mythic Vault' },
};

// Group labels for the page, in display order.
export const TROPHY_CATEGORIES = [
  { id: 'workout',    name: 'Iron',        emoji: '🏋️' },
  { id: 'streak',     name: 'Consistency', emoji: '🔥' },
  { id: 'cardio',     name: 'Endurance',   emoji: '🏃' },
  { id: 'level',      name: 'Progression', emoji: '⚡' },
  { id: 'duel',       name: 'Arena',       emoji: '⚔️' },
  { id: 'crew',       name: 'Crew',        emoji: '🛡️' },
  { id: 'social',     name: 'Community',   emoji: '💬' },
  { id: 'collection', name: 'Collection',  emoji: '🎁' },
];

// Each entry:
//   id          unique trophy id (must match migration 323's VALUES list)
//   name        display name
//   description criteria copy ("Log your 100th workout")
//   emoji       trophy art
//   tier        bronze | silver | gold | platinum | legendary
//   category    workout | streak | level | duel | crew | cardio | social | collection
//   ladder      key in LADDERS — which ladder this is a rung on
//   threshold   the signal value that earns it (drives the progress bar)
export const TROPHIES = [
  // ── Iron · sessions ─────────────────────────────────────────────
  { id: 'first_rep',       category: 'workout', ladder: 'sessions',  threshold: 1,       tier: 'bronze',    emoji: '🥉', name: 'First Rep',         description: 'Logged your first workout.' },
  { id: 'consistent',      category: 'workout', ladder: 'sessions',  threshold: 10,      tier: 'silver',    emoji: '🥈', name: 'Consistent',        description: '10 workouts logged.' },
  { id: 'committed',       category: 'workout', ladder: 'sessions',  threshold: 50,      tier: 'gold',      emoji: '🥇', name: 'Committed',         description: '50 workouts logged.' },
  { id: 'centurion',       category: 'workout', ladder: 'sessions',  threshold: 100,     tier: 'platinum',  emoji: '🏆', name: 'Centurion',         description: '100 workouts logged.' },

  // ── Iron · tonnage ──────────────────────────────────────────────
  // Thresholds are in POUNDS of lifetime volume. The old (dead)
  // achievements catalog had "one_ton_lifted" at target 1000 with no
  // unit anywhere — a ton is 2,000 lb, and being wrong about that is
  // how you ship a badge that means nothing.
  { id: 'tonnage_ton',     category: 'workout', ladder: 'tonnage',   threshold: 2000,    tier: 'bronze',    emoji: '🏋️', name: 'One Ton',           description: 'Moved 2,000 lb of lifetime volume.' },
  { id: 'tonnage_10t',     category: 'workout', ladder: 'tonnage',   threshold: 20000,   tier: 'silver',    emoji: '🏗️', name: 'Ten Ton',           description: 'Moved 20,000 lb of lifetime volume.' },
  { id: 'tonnage_100t',    category: 'workout', ladder: 'tonnage',   threshold: 200000,  tier: 'gold',      emoji: '🏛️', name: 'Hundred Ton',       description: 'Moved 200,000 lb of lifetime volume.' },
  { id: 'tonnage_million', category: 'workout', ladder: 'tonnage',   threshold: 1000000, tier: 'platinum',  emoji: '💎', name: 'Millionaire',       description: 'Moved 1,000,000 lb of lifetime volume.' },

  // ── Iron · variety ──────────────────────────────────────────────
  { id: 'variety_10',      category: 'workout', ladder: 'variety',   threshold: 10,      tier: 'bronze',    emoji: '🎽', name: 'Generalist',        description: 'Logged 10 different exercises.' },
  { id: 'variety_25',      category: 'workout', ladder: 'variety',   threshold: 25,      tier: 'silver',    emoji: '🎯', name: 'Well Rounded',      description: 'Logged 25 different exercises.' },
  { id: 'variety_50',      category: 'workout', ladder: 'variety',   threshold: 50,      tier: 'gold',      emoji: '📖', name: 'Encyclopedia',      description: 'Logged 50 different exercises.' },
  { id: 'variety_100',     category: 'workout', ladder: 'variety',   threshold: 100,     tier: 'platinum',  emoji: '🧭', name: 'Completionist',     description: 'Logged 100 different exercises.' },

  // ── Consistency · streak ────────────────────────────────────────
  { id: 'streak_spark',    category: 'streak',  ladder: 'streak',    threshold: 7,       tier: 'bronze',    emoji: '🔥', name: 'Spark',             description: '7-day workout streak.' },
  { id: 'streak_blaze',    category: 'streak',  ladder: 'streak',    threshold: 30,      tier: 'silver',    emoji: '🔥', name: 'Blaze',             description: '30-day workout streak.' },
  { id: 'streak_inferno',  category: 'streak',  ladder: 'streak',    threshold: 100,     tier: 'gold',      emoji: '🔥', name: 'Inferno',           description: '100-day workout streak.' },
  { id: 'streak_eternal',  category: 'streak',  ladder: 'streak',    threshold: 365,     tier: 'legendary', emoji: '🔥', name: 'Eternal Flame',     description: '365-day workout streak.' },

  // ── Consistency · longevity ─────────────────────────────────────
  // Months in which you logged at least one workout. Deliberately the
  // one ladder nobody can rush: it only moves with the calendar.
  { id: 'longevity_3',     category: 'streak',  ladder: 'longevity', threshold: 3,       tier: 'bronze',    emoji: '🌙', name: 'Three Moons',       description: 'Trained in 3 separate months.' },
  { id: 'longevity_6',     category: 'streak',  ladder: 'longevity', threshold: 6,       tier: 'silver',    emoji: '🗓️', name: 'Half Year',         description: 'Trained in 6 separate months.' },
  { id: 'longevity_12',    category: 'streak',  ladder: 'longevity', threshold: 12,      tier: 'gold',      emoji: '🎂', name: 'Anniversary',       description: 'Trained in 12 separate months.' },
  { id: 'longevity_24',    category: 'streak',  ladder: 'longevity', threshold: 24,      tier: 'platinum',  emoji: '🎖️', name: 'Veteran',           description: 'Trained in 24 separate months.' },

  // ── Consistency · quests ────────────────────────────────────────
  { id: 'quest_10',        category: 'streak',  ladder: 'quests',    threshold: 10,      tier: 'bronze',    emoji: '✅', name: 'Errand Runner',     description: 'Claimed 10 daily quests.' },
  { id: 'quest_100',       category: 'streak',  ladder: 'quests',    threshold: 100,     tier: 'silver',    emoji: '📋', name: 'Taskmaster',        description: 'Claimed 100 daily quests.' },
  { id: 'quest_500',       category: 'streak',  ladder: 'quests',    threshold: 500,     tier: 'gold',      emoji: '⚙️', name: 'Quest Machine',     description: 'Claimed 500 daily quests.' },

  { id: 'perfect_7',       category: 'streak',  ladder: 'perfect',   threshold: 7,       tier: 'bronze',    emoji: '💯', name: 'Perfect Week',      description: '7 days with every quest cleared.' },
  { id: 'perfect_30',      category: 'streak',  ladder: 'perfect',   threshold: 30,      tier: 'silver',    emoji: '🌟', name: 'Perfect Month',     description: '30 days with every quest cleared.' },
  { id: 'perfect_100',     category: 'streak',  ladder: 'perfect',   threshold: 100,     tier: 'gold',      emoji: '✨', name: 'Flawless Hundred',  description: '100 days with every quest cleared.' },

  // ── Endurance · single-session distance ─────────────────────────
  { id: 'cardio_5k',       category: 'cardio',  ladder: 'cardio',    threshold: 5000,    tier: 'bronze',    emoji: '🏃', name: '5K Club',           description: 'Logged a 5K+ cardio session.' },
  { id: 'cardio_10k',      category: 'cardio',  ladder: 'cardio',    threshold: 10000,   tier: 'silver',    emoji: '🏃', name: '10K Club',          description: 'Logged a 10K+ cardio session.' },
  // 21,097 m, not 21,100 — that is the official half-marathon distance
  // and the number migration 167 already grants on. A mismatch here
  // would show "21,098 / 21,100" on a badge the server already gave you.
  { id: 'cardio_half',     category: 'cardio',  ladder: 'cardio',    threshold: 21097,   tier: 'gold',      emoji: '🏆', name: 'Half Marathoner',   description: 'Logged a 21.1K+ cardio session.' },
  { id: 'cardio_marathon', category: 'cardio',  ladder: 'cardio',    threshold: 42195,   tier: 'legendary', emoji: '🏅', name: 'Marathoner',        description: 'Logged a full 42.2K cardio session.' },

  // ── Endurance · lifetime distance ───────────────────────────────
  { id: 'distance_50k',    category: 'cardio',  ladder: 'distance',  threshold: 50000,   tier: 'bronze',    emoji: '🥾', name: 'Getting Going',     description: '50 km of lifetime cardio distance.' },
  { id: 'distance_250k',   category: 'cardio',  ladder: 'distance',  threshold: 250000,  tier: 'silver',    emoji: '🛣️', name: 'Long Hauler',       description: '250 km of lifetime cardio distance.' },
  { id: 'distance_1000k',  category: 'cardio',  ladder: 'distance',  threshold: 1000000, tier: 'gold',      emoji: '🌍', name: 'Four Digits',       description: '1,000 km of lifetime cardio distance.' },

  // ── Endurance · cross-training ──────────────────────────────────
  { id: 'cross_3',         category: 'cardio',  ladder: 'cross',     threshold: 3,       tier: 'bronze',    emoji: '🔀', name: 'Mixed Bag',         description: 'Logged 3 different cardio activities.' },
  { id: 'cross_5',         category: 'cardio',  ladder: 'cross',     threshold: 5,       tier: 'silver',    emoji: '🤸', name: 'Cross Trainer',     description: 'Logged 5 different cardio activities.' },
  { id: 'cross_8',         category: 'cardio',  ladder: 'cross',     threshold: 8,       tier: 'gold',      emoji: '🃏', name: 'Jack of All',       description: 'Logged 8 different cardio activities.' },

  // ── Progression · level ─────────────────────────────────────────
  { id: 'level_tier1',     category: 'level',   ladder: 'level',     threshold: 10,      tier: 'bronze',    emoji: '⚡', name: 'Tier 1',            description: 'Reached Level 10.' },
  { id: 'level_tier2',     category: 'level',   ladder: 'level',     threshold: 25,      tier: 'silver',    emoji: '⚡', name: 'Tier 2',            description: 'Reached Level 25.' },
  { id: 'level_tier3',     category: 'level',   ladder: 'level',     threshold: 50,      tier: 'gold',      emoji: '⚡', name: 'Tier 3',            description: 'Reached Level 50.' },
  { id: 'level_apex',      category: 'level',   ladder: 'level',     threshold: 100,     tier: 'legendary', emoji: '⚡', name: 'Apex',              description: 'Reached Level 100.' },

  // ── Progression · prestige ──────────────────────────────────────
  { id: 'prestige_1',      category: 'level',   ladder: 'prestige',  threshold: 1,       tier: 'gold',      emoji: '🔄', name: 'Reborn',            description: 'Prestiged once.' },
  { id: 'prestige_3',      category: 'level',   ladder: 'prestige',  threshold: 3,       tier: 'platinum',  emoji: '⚒️', name: 'Thrice Forged',     description: 'Prestiged 3 times.' },
  { id: 'prestige_5',      category: 'level',   ladder: 'prestige',  threshold: 5,       tier: 'legendary', emoji: '♾️', name: 'Eternal Return',    description: 'Prestiged 5 times.' },

  // ── Progression · goals ─────────────────────────────────────────
  { id: 'goal_first',      category: 'level',   ladder: 'goals',     threshold: 1,       tier: 'bronze',    emoji: '🎯', name: 'First Target',      description: 'Completed your first goal.' },
  { id: 'goal_10',         category: 'level',   ladder: 'goals',     threshold: 10,      tier: 'silver',    emoji: '🏹', name: 'Goal Getter',       description: 'Completed 10 goals.' },
  { id: 'goal_50',         category: 'level',   ladder: 'goals',     threshold: 50,      tier: 'gold',      emoji: '🔱', name: 'Relentless',        description: 'Completed 50 goals.' },

  // ── Arena · duels ───────────────────────────────────────────────
  { id: 'duel_challenger', category: 'duel',    ladder: 'duel',      threshold: 1,       tier: 'bronze',    emoji: '⚔️', name: 'Challenger',        description: 'Won your first duel.' },
  { id: 'duel_champion',   category: 'duel',    ladder: 'duel',      threshold: 10,      tier: 'silver',    emoji: '⚔️', name: 'Champion',          description: 'Won 10 duels.' },
  { id: 'duel_gladiator',  category: 'duel',    ladder: 'duel',      threshold: 50,      tier: 'gold',      emoji: '🗡️', name: 'Gladiator',         description: 'Won 50 duels.' },
  { id: 'duel_immortal',   category: 'duel',    ladder: 'duel',      threshold: 200,     tier: 'platinum',  emoji: '👑', name: 'Immortal',          description: 'Won 200 duels.' },

  // ── Arena · bounties ────────────────────────────────────────────
  { id: 'bounty_1',        category: 'duel',    ladder: 'bounty',    threshold: 1,       tier: 'bronze',    emoji: '🎯', name: 'Bounty Hunter',     description: 'Claimed your first bounty.' },
  { id: 'bounty_10',       category: 'duel',    ladder: 'bounty',    threshold: 10,      tier: 'silver',    emoji: '💰', name: 'Collector',         description: 'Claimed 10 bounties.' },
  { id: 'bounty_50',       category: 'duel',    ladder: 'bounty',    threshold: 50,      tier: 'gold',      emoji: '🤠', name: 'Most Wanted',       description: 'Claimed 50 bounties.' },

  // ── Arena · gauntlet ────────────────────────────────────────────
  // `binary` marks a rung that is a yes/no rather than a count, so the
  // page renders a state instead of an "x / y" bar. Without it this one
  // would read "5 / 999", which is not a thing anyone is 5/999 of.
  { id: 'gauntlet_5',      category: 'duel',    ladder: 'gauntlet',  threshold: 5,       tier: 'bronze',    emoji: '🧗', name: 'Gauntlet Runner',   description: 'Cleared 5 gauntlet challenges.' },
  { id: 'gauntlet_path',   category: 'duel',    ladder: 'gauntlet',  threshold: 1, binary: true, signal: 'gauntletPath', tier: 'gold', emoji: '🏔️', name: 'Gauntlet Cleared',  description: 'Completed the full gauntlet path.' },

  // ── Crew ────────────────────────────────────────────────────────
  { id: 'crew_squad',      category: 'crew',    ladder: 'crew',      threshold: 1,       tier: 'bronze',    emoji: '🛡️', name: 'Squad Member',      description: 'Joined your first crew.' },
  { id: 'crewwar_1',       category: 'crew',    ladder: 'crewwar',   threshold: 1,       tier: 'bronze',    emoji: '🚩', name: 'Enlisted',          description: 'Contributed to your first crew war.' },
  { id: 'crewwar_10',      category: 'crew',    ladder: 'crewwar',   threshold: 10,      tier: 'silver',    emoji: '⚔️', name: 'War Veteran',       description: 'Contributed to 10 crew wars.' },
  { id: 'crewwar_50',      category: 'crew',    ladder: 'crewwar',   threshold: 50,      tier: 'gold',      emoji: '🏰', name: 'Warlord',           description: 'Contributed to 50 crew wars.' },

  // ── Community · hub ─────────────────────────────────────────────
  { id: 'post_1',          category: 'social',  ladder: 'social',    threshold: 1,       tier: 'bronze',    emoji: '💬', name: 'First Post',        description: 'Posted to the Hub.' },
  { id: 'post_10',         category: 'social',  ladder: 'social',    threshold: 10,      tier: 'silver',    emoji: '📣', name: 'Regular',           description: '10 Hub posts.' },
  { id: 'post_50',         category: 'social',  ladder: 'social',    threshold: 50,      tier: 'gold',      emoji: '📢', name: 'Voice of the Hub',  description: '50 Hub posts.' },
  { id: 'post_200',        category: 'social',  ladder: 'social',    threshold: 200,     tier: 'platinum',  emoji: '🎙️', name: 'Hub Legend',        description: '200 Hub posts.' },

  // ── Community · gym check-ins ───────────────────────────────────
  { id: 'checkin_1',       category: 'social',  ladder: 'gym',       threshold: 1,       tier: 'bronze',    emoji: '📍', name: 'Showed Up',         description: 'Checked in at a gym.' },
  { id: 'checkin_25',      category: 'social',  ladder: 'gym',       threshold: 25,      tier: 'silver',    emoji: '🏋️‍♀️', name: 'Local',             description: '25 gym check-ins.' },
  { id: 'checkin_100',     category: 'social',  ladder: 'gym',       threshold: 100,     tier: 'gold',      emoji: '🏛️', name: 'Regular Fixture',   description: '100 gym check-ins.' },
  { id: 'checkin_365',     category: 'social',  ladder: 'gym',       threshold: 365,     tier: 'platinum',  emoji: '🗿', name: 'Institution',       description: '365 gym check-ins.' },

  // ── Collection ──────────────────────────────────────────────────
  { id: 'capsule_1',       category: 'collection', ladder: 'capsule', threshold: 1,      tier: 'bronze',    emoji: '🎁', name: 'First Drop',        description: 'Opened your first capsule.' },
  { id: 'capsule_25',      category: 'collection', ladder: 'capsule', threshold: 25,     tier: 'silver',    emoji: '📦', name: 'Hoarder',           description: 'Opened 25 capsules.' },
  { id: 'capsule_100',     category: 'collection', ladder: 'capsule', threshold: 100,    tier: 'gold',      emoji: '🔐', name: 'Vault Keeper',      description: 'Opened 100 capsules.' },

  { id: 'relic_1',         category: 'collection', ladder: 'relic',   threshold: 1,      tier: 'gold',      emoji: '🌟', name: 'Legendary Find',    description: 'Owned your first legendary item.' },
  { id: 'relic_5',         category: 'collection', ladder: 'relic',   threshold: 5,      tier: 'platinum',  emoji: '💫', name: 'Legend Collector',  description: 'Owned 5 legendary items.' },
  { id: 'relic_25',        category: 'collection', ladder: 'relic',   threshold: 25,     tier: 'legendary', emoji: '🔮', name: 'Mythic Vault',      description: 'Owned 25 legendary items.' },
];

export const TROPHY_BY_ID = Object.fromEntries(TROPHIES.map(t => [t.id, t]));

// ── League season trophies ────────────────────────────────────────────────
//
// These cannot live in TROPHIES, because a new one is minted every 28 days
// and a static catalog would need editing on every roll. They are resolved
// from the id instead: `league_s{n}_{tier}` and `league_s{n}_champion`, both
// written by award_league_season_internal (migration 312).
//
// `TROPHIES.length` is the denominator for the "12 / 40 earned" counter on
// the profile, so season trophies are deliberately NOT added to it — an
// unreachable denominator that grows forever would make the collection look
// permanently unfinished.

const SEASON_TROPHY_RE = /^league_s(\d+)_(bronze|silver|gold|platinum|diamond|legend|champion)$/;

// TROPHY_TIERS has no `diamond` step, so diamond borrows platinum's ramp and
// both legend and champion take `legendary`.
const SEASON_TIER_MAP = {
  bronze: 'bronze', silver: 'silver', gold: 'gold',
  platinum: 'platinum', diamond: 'platinum',
  legend: 'legendary', champion: 'legendary',
};

const SEASON_EMOJI = {
  bronze: '🥉', silver: '🥈', gold: '🥇',
  platinum: '💠', diamond: '💎', legend: '👑', champion: '👑',
};

/** Parsed season trophy, or null if `id` isn't one. */
export function parseSeasonTrophy(id) {
  const m = SEASON_TROPHY_RE.exec(id || '');
  if (!m) return null;
  const season = Number(m[1]);
  const kind = m[2];
  const isChampion = kind === 'champion';
  const label = kind.charAt(0).toUpperCase() + kind.slice(1);
  return {
    id,
    season,
    kind,
    isChampion,
    category: 'league',
    tier: SEASON_TIER_MAP[kind] || 'bronze',
    emoji: SEASON_EMOJI[kind] || '🎖️',
    name: isChampion ? `Champion, S${season}` : `Season ${season} ${label}`,
    description: isChampion
      ? `Won season ${season} outright. Minted once — nobody else can earn this one.`
      : `Reached ${label} in season ${season}.`,
  };
}

// ── Infinite ladder tails ─────────────────────────────────────────
//
// Past the last named rung, ids are generated rather than enumerated:
// `sessions_x1` is 200 workouts, `sessions_x2` is 300, and so on. Same
// trick as the league season trophies above, for the same reason — the
// alternative is a catalog that has to be edited every time somebody
// out-trains it.
//
// Tail rung k requires `tailBase + k * tailStep` and displays as the
// top rung's name in Roman numerals: k=1 → "Centurion II".
//
// Like season trophies, these are NOT in TROPHIES — see the header.

const TAIL_RE = /^([a-z]+)_x(\d+)$/;

// A cap on generated rungs, mirrored in migration 323. Nobody is
// legitimately 50 tail-rungs deep, so a number past this means corrupt
// data rather than a very dedicated user, and it stops one bad
// `total_volume_lbs` from minting thousands of rows.
export const TAIL_CAP = 50;

const ROMAN = [
  [1000, 'M'], [900, 'CM'], [500, 'D'], [400, 'CD'], [100, 'C'], [90, 'XC'],
  [50, 'L'], [40, 'XL'], [10, 'X'], [9, 'IX'], [5, 'V'], [4, 'IV'], [1, 'I'],
];

/** 4 → "IV". Used for tail rung numerals. */
export function toRoman(n) {
  let out = '';
  let rest = Math.max(0, Math.floor(n));
  for (const [value, numeral] of ROMAN) {
    while (rest >= value) { out += numeral; rest -= value; }
  }
  return out;
}

/** Parsed tail trophy, or null if `id` isn't one. */
export function parseLadderTail(id) {
  const m = TAIL_RE.exec(id || '');
  if (!m) return null;
  const ladderId = m[1];
  const k = Number(m[2]);
  const ladder = LADDERS[ladderId];
  // A tail on a ladder that has none is not a trophy — it's a typo or a
  // forged id. Resolve it to null so it renders as nothing rather than
  // as a plausible-looking badge.
  if (!ladder || ladder.tailBase == null || k < 1 || k > TAIL_CAP) return null;

  const threshold = ladder.tailBase + k * ladder.tailStep;
  // Tails sit above the top named rung, so they take the top tier of
  // the ramp. There is nowhere further to escalate.
  return {
    id,
    ladder: ladderId,
    category: ladder.category,
    tier: 'legendary',
    emoji: '♾️',
    threshold,
    isTail: true,
    name: `${ladder.tailName} ${toRoman(k + 1)}`,
    description: `${threshold.toLocaleString()} ${ladder.unit}`.trim(),
  };
}

export function getTrophy(id) {
  return TROPHY_BY_ID[id] || parseSeasonTrophy(id) || parseLadderTail(id) || null;
}

// ── "What's next" ─────────────────────────────────────────────────
//
// The whole point of the ladder structure: given where someone is on a
// ladder, hand back the ONE rung they're working toward. The page shows
// this rather than the full wall, so finishing a rung immediately
// replaces it with the next one instead of leaving a gap.
//
// Returns null only for a ladder that has genuinely ended — the
// deliberate dead ends (see LADDERS). Everything else always answers.
const RUNGS_BY_LADDER = TROPHIES.reduce((acc, t) => {
  if (!t.ladder) return acc;
  (acc[t.ladder] ||= []).push(t);
  return acc;
}, {});
Object.values(RUNGS_BY_LADDER).forEach(list => list.sort((a, b) => a.threshold - b.threshold));

/** Every named rung on a ladder, lowest threshold first. */
export function rungsFor(ladderId) {
  return RUNGS_BY_LADDER[ladderId] || [];
}

/**
 * The next rung on `ladderId` for someone whose signal reads `value`.
 * Falls through the named rungs, then into the generated tail.
 */
export function nextRung(ladderId, value = 0) {
  const ladder = LADDERS[ladderId];
  if (!ladder) return null;

  const named = rungsFor(ladderId).find(r => value < r.threshold);
  if (named) return named;

  // Past every named rung — walk into the tail.
  if (ladder.tailBase == null) return null;
  const k = Math.floor((value - ladder.tailBase) / ladder.tailStep) + 1;
  return parseLadderTail(`${ladderId}_x${Math.min(Math.max(k, 1), TAIL_CAP)}`);
}

/**
 * Progress toward `trophy` given the caller's signal value, as
 * { value, target, pct, done }. `pct` is clamped to 0–100.
 */
export function rungProgress(trophy, value = 0) {
  const target = trophy?.threshold || 0;
  const done = target > 0 && value >= target;
  const pct = target > 0 ? Math.min(100, Math.max(0, (value / target) * 100)) : 0;
  return { value, target, pct, done };
}
