[build]
  command = "npm run build"
  publish = "dist"

[build.environment]
  VITE_SUPABASE_URL = "https://ebvqxuwfiptcmlkhflfj.supabase.co"
  VITE_SUPABASE_ANON_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVidnF4dXdmaXB0Y21sa2hmbGZqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Nzc4MzYwNDQsImV4cCI6MjA5MzQxMjA0NH0.c6VsWcN85j-3eF1EXx-nsTqcu6-ef0JgGH4OlH0HZKY"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
