// scripts/split-i18n.mjs
//
// Generates per-language i18n aggregate files from the existing part files
// in src/lib/i18n-*.js, so the runtime can dynamic-import only the user's
// active language instead of bundling all 15 languages into the entry.
//
// Reads: src/lib/i18n-*.js (NOT i18n-check.js or i18n.js — those are infra)
// Writes: src/lib/i18n-langs/<code>.js  for each supported language
//
// Each generated file looks like:
//   // AUTOGENERATED — DO NOT EDIT. Run `npm run build:i18n` to regenerate.
//   export default {
//     'app.name': 'Flexyn',
//     'nav.dashboard': 'Dashboard',
//     ...
//   };
//
// Strategy: import each part file as ESM, merge its `<lang>` blocks into
// a per-language map, dedupe keys (later parts win — matches the runtime
// merge in i18n.js), write each map out as a stable JSON-like ESM module.

import { readdir, writeFile, mkdir, rm } from 'node:fs/promises';
import { existsSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import path from 'node:path';
import { createJiti } from 'jiti';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const LIB_DIR = path.resolve(__dirname, '..', 'src', 'lib');
const OUT_DIR = path.join(LIB_DIR, 'i18n-langs');

// Use jiti to load the part files — they use extension-less imports
// (Vite's resolver handles that at build/dev time, but Node ESM does
// not). jiti gives us a CJS-style require that resolves the same way
// Vite would.
const jiti = createJiti(import.meta.url, {
  // Auto-add `.js` / `.jsx` / `.ts` / `.tsx` on missing extensions.
  extensions: ['.js', '.jsx', '.ts', '.tsx', '.json'],
  // Cache off — every script run starts fresh.
  cache: false,
  // No interop tweaks needed; the part files export plain ESM.
});

// Supported languages — must match SUPPORTED_LANGUAGES in src/lib/i18n.js
const LANGS = ['en', 'es', 'fr', 'de', 'pt', 'it', 'ja', 'ko', 'zh', 'ar', 'hi', 'ru', 'tr', 'pl', 'nl'];

// Files in src/lib whose name starts with `i18n-` AND which export a
// translation object. The check file (`i18n-check.js`) and root
// (`i18n.js`) are skipped because they don't carry translation data.
const SKIP_FILES = new Set(['i18n-check.js', 'i18n.js']);

async function main() {
  console.log('[split-i18n] Scanning', LIB_DIR);
  const entries = await readdir(LIB_DIR);
  const partFiles = entries.filter(
    (f) => f.startsWith('i18n-') && f.endsWith('.js') && !SKIP_FILES.has(f) && !f.startsWith('i18n-langs')
  );
  console.log(`[split-i18n] Found ${partFiles.length} part files`);

  // Accumulate per-language merged maps.
  // Order matters: later files OVERWRITE earlier ones — matches the
  // mergeTranslations semantics in i18n.js so we can't introduce a
  // silent drift between the split and the runtime fallback.
  const merged = Object.fromEntries(LANGS.map((l) => [l, {}]));

  for (const file of partFiles) {
    const absPath = path.join(LIB_DIR, file);
    let mod;
    try {
      mod = await jiti.import(absPath);
    } catch (err) {
      console.error(`[split-i18n] Failed to import ${file}:`, err.message);
      process.exit(1);
    }
    // Each part file exports one named const that's an object keyed by
    // language. The export NAME varies (`translations_p1`, `goalsI18n`,
    // `dashboardRedesignI18n` etc.). Find the first non-default export
    // that has language keys.
    const exports = Object.values(mod);
    const data = exports.find(
      (v) => v && typeof v === 'object' && LANGS.some((l) => l in v)
    );
    if (!data) {
      console.warn(`[split-i18n] No language-keyed export in ${file}, skipping`);
      continue;
    }

    for (const lang of LANGS) {
      const block = data[lang];
      if (!block) continue;
      Object.assign(merged[lang], block);
    }
  }

  // Reset output directory (clean every run so a deleted key disappears).
  if (existsSync(OUT_DIR)) {
    await rm(OUT_DIR, { recursive: true, force: true });
  }
  await mkdir(OUT_DIR, { recursive: true });

  let totalKeys = 0;
  for (const lang of LANGS) {
    const keys = Object.keys(merged[lang]);
    totalKeys += keys.length;
    const sorted = Object.fromEntries(
      Object.entries(merged[lang]).sort(([a], [b]) => a.localeCompare(b))
    );
    const body = JSON.stringify(sorted, null, 2);
    const fileSrc =
      `// AUTOGENERATED by scripts/split-i18n.mjs — DO NOT EDIT.\n` +
      `// Edit the source part files (src/lib/i18n-*.js) and run\n` +
      `// \`npm run build:i18n\` to regenerate.\n` +
      `// Language: ${lang}  Keys: ${keys.length}\n` +
      `export default ${body};\n`;
    const outPath = path.join(OUT_DIR, `${lang}.js`);
    await writeFile(outPath, fileSrc, 'utf8');
    console.log(`[split-i18n] wrote i18n-langs/${lang}.js  (${keys.length} keys)`);
  }
  console.log(`[split-i18n] Done — ${totalKeys} total keys across ${LANGS.length} languages`);
}

main().catch((err) => {
  console.error('[split-i18n] Fatal error:', err);
  process.exit(1);
});
