// scripts/split-i18n.mjs
//
// Generates per-language i18n aggregate files from the existing part files
// in src/lib/i18n-*.js, so the runtime can dynamic-import only the user's
// active language instead of bundling all 15 languages into the entry.
//
// Reads: src/lib/i18n-*.js (NOT i18n-check.js or i18n.js — those are infra)
// Writes: src/lib/i18n-langs/<code>.js  for each supported language
//
// Each generated file looks like:
//   // AUTOGENERATED — DO NOT EDIT. Run `npm run build:i18n` to regenerate.
//   export default {
//     'app.name': 'Flexyn',
//     'nav.dashboard': 'Dashboard',
//     ...
//   };
//
// Strategy: import each part file as ESM, merge its `<lang>` blocks into
// a per-language map, dedupe keys (later parts win — matches the runtime
// merge in i18n.js), write each map out as a stable JSON-like ESM module.

import { readdir, readFile, writeFile, mkdir, rm } from 'node:fs/promises';
import { existsSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import path from 'node:path';
import { createJiti } from 'jiti';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const LIB_DIR = path.resolve(__dirname, '..', 'src', 'lib');
const OUT_DIR = path.join(LIB_DIR, 'i18n-langs');

// Use jiti to load the part files — they use extension-less imports
// (Vite's resolver handles that at build/dev time, but Node ESM does
// not). jiti gives us a CJS-style require that resolves the same way
// Vite would.
const jiti = createJiti(import.meta.url, {
  // Auto-add `.js` / `.jsx` / `.ts` / `.tsx` on missing extensions.
  extensions: ['.js', '.jsx', '.ts', '.tsx', '.json'],
  // Cache off — every script run starts fresh.
  cache: false,
  // No interop tweaks needed; the part files export plain ESM.
});

// Supported languages — must match SUPPORTED_LANGUAGES in src/lib/i18n.js
const LANGS = ['en', 'es', 'fr', 'de', 'pt', 'it', 'ja', 'ko', 'zh', 'ar', 'hi', 'ru', 'tr', 'pl', 'nl'];

// Files in src/lib whose name starts with `i18n-` AND which export a
// translation object. The check file (`i18n-check.js`) and root
// (`i18n.js`) are skipped because they don't carry translation data.
const SKIP_FILES = new Set(['i18n-check.js', 'i18n.js']);

async function main() {
  console.log('[split-i18n] Scanning', LIB_DIR);
  const entries = await readdir(LIB_DIR);
  const partFiles = entries.filter(
    (f) => f.startsWith('i18n-') && f.endsWith('.js') && !SKIP_FILES.has(f) && !f.startsWith('i18n-langs')
  );
  console.log(`[split-i18n] Found ${partFiles.length} part files`);

  // Accumulate per-language merged maps.
  // Order matters: later files OVERWRITE earlier ones — matches the
  // mergeTranslations semantics in i18n.js so we can't introduce a
  // silent drift between the split and the runtime fallback.
  const merged = Object.fromEntries(LANGS.map((l) => [l, {}]));

  // ── Duplicate-language-block guard ────────────────────────────────────────
  //
  // This HAS to read the raw source. By the time jiti.import() hands back an
  // object, JavaScript has already resolved `{ pt: {...}, ..., pt: {...} }` by
  // keeping the LAST block and discarding the earlier one — silently, with no
  // error and no warning. The merge below can only ever see the survivor, so
  // the loss is structurally invisible downstream.
  //
  // It had happened three times in 41 files. Only one caused real damage, and
  // it picked the worst possible key to lose: `onboarding.welcome.languageHint`
  // for pt, it, ja and ko — the string whose entire job is telling someone who
  // can't read the current language how to switch. It fell back to English, so
  // a Portuguese speaker on the welcome screen was asked "Don't speak English?".
  // The correct Portuguese was four lines above the block that overwrote it.
  //
  // It must be scoped PER OBJECT LITERAL, not per file. `i18n-warn.js` holds
  // two separate literals — a plain one and a second passed to a merge helper
  // — each legitimately declaring all 15 languages. A file-wide count calls
  // that a duplicate and blocks a correct build, which is worse than no guard
  // at all. Hence the brace-depth scan below rather than a bare regex.
  //
  // The scan skips string contents, because translation VALUES contain braces
  // (`{count}`, `{streak}` placeholders) and a naive depth counter drifts on
  // the first one it meets.
  const dupErrors = [];
  for (const file of partFiles) {
    const raw = await readFile(path.join(LIB_DIR, file), 'utf8');
    const counts = new Map();   // lang -> occurrences, reset per top-level literal
    let depth = 0;
    let quote = null;           // ' " or ` while inside a string

    for (let i = 0; i < raw.length; i++) {
      const c = raw[i];

      if (quote) {
        if (c === '\\') { i++; continue; }
        if (c === quote) quote = null;
        continue;
      }
      if (c === "'" || c === '"' || c === '`') { quote = c; continue; }
      if (c === '/' && raw[i + 1] === '/') { i = raw.indexOf('\n', i); if (i < 0) break; continue; }
      if (c === '/' && raw[i + 1] === '*') { i = raw.indexOf('*/', i) + 1; if (i < 1) break; continue; }

      if (c === '{') {
        depth++;
        // A language block sits at depth 2: the outer literal opened at
        // depth 1, and `en: {` opens depth 2. Look backwards for its key.
        if (depth === 2) {
          const before = raw.slice(Math.max(0, i - 24), i);
          const m = before.match(/([a-z]{2})\s*:\s*$/);
          if (m && LANGS.includes(m[1])) {
            counts.set(m[1], (counts.get(m[1]) || 0) + 1);
          }
        }
        continue;
      }
      if (c === '}') {
        depth--;
        if (depth <= 0) {
          // Left the literal — record anything duplicated inside it, then reset.
          const dups = [...counts].filter(([, n]) => n > 1);
          if (dups.length) {
            dupErrors.push(
              `  ${file} — ${dups.map(([l, n]) => `'${l}' declared ${n}×`).join(', ')}`
            );
          }
          counts.clear();
          depth = 0;
        }
      }
    }
  }
  if (dupErrors.length) {
    console.error(
      '\n[split-i18n] DUPLICATE LANGUAGE BLOCKS — build stopped.\n\n' +
      dupErrors.join('\n') +
      '\n\nA language may appear at most once per part file. JavaScript keeps\n' +
      'the last block and throws the earlier one away without warning, so\n' +
      'every key in the earlier block is silently lost. Merge them into one\n' +
      'block per language.\n'
    );
    process.exit(1);
  }

  for (const file of partFiles) {
    const absPath = path.join(LIB_DIR, file);
    let mod;
    try {
      mod = await jiti.import(absPath);
    } catch (err) {
      console.error(`[split-i18n] Failed to import ${file}:`, err.message);
      process.exit(1);
    }
    // Each part file exports one named const that's an object keyed by
    // language. The export NAME varies (`translations_p1`, `goalsI18n`,
    // `dashboardRedesignI18n` etc.). Find the first non-default export
    // that has language keys.
    const exports = Object.values(mod);
    const data = exports.find(
      (v) => v && typeof v === 'object' && LANGS.some((l) => l in v)
    );
    if (!data) {
      console.warn(`[split-i18n] No language-keyed export in ${file}, skipping`);
      continue;
    }

    for (const lang of LANGS) {
      const block = data[lang];
      if (!block) continue;
      Object.assign(merged[lang], block);
    }
  }

  // Reset output directory (clean every run so a deleted key disappears).
  if (existsSync(OUT_DIR)) {
    await rm(OUT_DIR, { recursive: true, force: true });
  }
  await mkdir(OUT_DIR, { recursive: true });

  let totalKeys = 0;
  for (const lang of LANGS) {
    const keys = Object.keys(merged[lang]);
    totalKeys += keys.length;
    const sorted = Object.fromEntries(
      Object.entries(merged[lang]).sort(([a], [b]) => a.localeCompare(b))
    );
    const body = JSON.stringify(sorted, null, 2);
    const fileSrc =
      `// AUTOGENERATED by scripts/split-i18n.mjs — DO NOT EDIT.\n` +
      `// Edit the source part files (src/lib/i18n-*.js) and run\n` +
      `// \`npm run build:i18n\` to regenerate.\n` +
      `// Language: ${lang}  Keys: ${keys.length}\n` +
      `export default ${body};\n`;
    const outPath = path.join(OUT_DIR, `${lang}.js`);
    await writeFile(outPath, fileSrc, 'utf8');
    console.log(`[split-i18n] wrote i18n-langs/${lang}.js  (${keys.length} keys)`);
  }
  console.log(`[split-i18n] Done — ${totalKeys} total keys across ${LANGS.length} languages`);
}

main().catch((err) => {
  console.error('[split-i18n] Fatal error:', err);
  process.exit(1);
});
