-- migration 051: weekly_debriefs table
-- Stores auto-generated Sunday debrief cards per user.
-- Generated by the generateWeeklyDebriefs edge function (pg_cron, Sunday nights).
-- Frontend renders from the data JSONB so card design can evolve without migrating rows.

CREATE TABLE IF NOT EXISTS public.weekly_debriefs (
  id            UUID         PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id       UUID         REFERENCES auth.users(id) ON DELETE CASCADE NOT NULL,
  user_email    TEXT         NOT NULL,
  week_number   INT          NOT NULL,
  year          INT          NOT NULL,
  week_label    TEXT         NOT NULL,
  epoch_id      UUID,        -- nullable; reserved for future Epochs feature
  epoch_name    TEXT,
  data          JSONB        NOT NULL DEFAULT '{}',
  created_at    TIMESTAMPTZ  DEFAULT NOW(),
  UNIQUE(user_id, week_number, year)
);

ALTER TABLE public.weekly_debriefs ENABLE ROW LEVEL SECURITY;

-- Users can only read their own debriefs
CREATE POLICY "weekly_debriefs_select_own"
  ON public.weekly_debriefs
  FOR SELECT
  USING (auth.uid() = user_id);

-- Service role (edge function) can write on behalf of any user
CREATE POLICY "weekly_debriefs_service_role_all"
  ON public.weekly_debriefs
  FOR ALL
  USING (true)
  WITH CHECK (true);

-- ── Cron: trigger generateWeeklyDebriefs every Sunday at 20:00 UTC ─────────────
-- Requires pg_cron + pg_net extensions (both enabled in migration 037).
-- The edge function URL and cron secret must be set as DB settings:
--   ALTER DATABASE postgres SET app.debrief_func_url = 'https://<ref>.functions.supabase.co/generateWeeklyDebriefs';
--   ALTER DATABASE postgres SET app.debrief_cron_secret = '<secret>';
-- These are set separately via the apply_051_cron.sql helper below.
