// App-wide i18n coverage guards.
//
// These lock the invariants that produce visible damage, and deliberately
// do NOT assert 100% coverage — the app ships some features English-only
// on purpose (see CLAUDE.md's out-of-scope list), so a "no gaps" test
// would just get skipped past.
//
// The failure modes, worst first:
//
//   1. A key resolving to NOTHING. getTranslation falls back
//      `language → en → the raw key`, so a key absent from `en` too
//      renders its own path — "challenge.duration" on a button. This must
//      stay at zero.
//   2. A PARTIAL gap: translated in ten languages, missing in four. Shows
//      as one English line inside an otherwise-translated screen. Tracked
//      with a ratchet so it can shrink but not silently grow.
//
// `node scripts/i18n-audit.mjs` reports the same data in detail;
// `--partial` lists exactly which keys and languages.

import { describe, it, expect } from 'vitest';
import fs from 'fs';
import path from 'path';
import { execFileSync } from 'child_process';

const LANGS = ['en','es','fr','de','pt','it','ja','ko','zh','ar','hi','ru','tr','pl','nl'];
const OTHERS = LANGS.filter(l => l !== 'en');
const DIR = 'src/locales';

const keys = Object.fromEntries(LANGS.map(l => [
  l,
  new Set(Object.keys(JSON.parse(fs.readFileSync(path.join(DIR, `${l}.json`), 'utf8')))),
]));
const en = keys.en;

/** Every bare `t('key')` in the app, with comments stripped. */
function collectCallSites() {
  const bare = new Map();
  const safe = new Set();
  (function walk(dir) {
    for (const e of fs.readdirSync(dir, { withFileTypes: true })) {
      const p = path.join(dir, e.name);
      if (e.isDirectory()) {
        if (!/__tests__|node_modules|locales/.test(e.name)) walk(p);
        continue;
      }
      if (!/\.jsx?$/.test(e.name) || /^i18n-/.test(e.name)) continue;
      const src = fs.readFileSync(p, 'utf8')
        .replace(/\/\*[\s\S]*?\*\//g, '')
        .replace(/^\s*\/\/.*$/gm, '');
      // Backticks included: a template literal with no ${} is a constant
      // key and several call sites write one. Must stay identical to the
      // scan in scripts/i18n-baseline.mjs, or the guard below compares a
      // count against a ceiling generated by a different measurement.
      // tF / tf are live aliases (Dashboard.jsx's section headings use one).
      for (const m of src.matchAll(/\b(?:tFallback|tF|tf)\(\s*['"`]([\w.]+)['"`]\s*,/g)) safe.add(m[1]);
      // Keys held as <name>Key data properties — see the note in
      // scripts/i18n-audit.mjs. The call site passes a variable, so a
      // scan anchored on the call cannot see these at all.
      for (const m of src.matchAll(/\w*Key:\s*'([\w.]+)'/g)) if (m[1].includes('.')) safe.add(m[1]);
      for (const m of src.matchAll(/\bt\(\s*['"`]([\w.]+)['"`]\s*\)(?!\s*(?:\|\||\?\?))/g)) {
        if (!bare.has(m[1])) bare.set(m[1], new Set());
        bare.get(m[1]).add(p.replace(/^src\//, ''));
      }
    }
  })('src');
  return { bare, safe };
}

describe('no key can render as a raw key path', () => {
  it('every bare t() call resolves to something', () => {
    const { bare, safe } = collectCallSites();
    const unresolvable = [...bare.keys()]
      .filter(k => !en.has(k) && !safe.has(k))
      .map(k => `${k} (${[...bare.get(k)].join(', ')})`)
      .sort();
    // A bare t('x') with no English definition puts the literal string
    // 'x' on screen. Either add it to a part file or switch the call to
    // tFallback('x', 'English').
    expect(unresolvable).toEqual([]);
  });
});

describe('every language file is loadable and non-trivial', () => {
  it.each(LANGS)('%s has a populated aggregate', (lang) => {
    expect(keys[lang].size).toBeGreaterThan(1000);
  });

  it('no language has keys English lacks', () => {
    // The reverse direction: a key only in `es` is dead weight nothing
    // can reach, since every call site is written against the English set.
    for (const l of OTHERS) {
      const orphans = [...keys[l]].filter(k => !en.has(k));
      expect(orphans, `${l} has keys absent from en: ${orphans.slice(0, 5).join(', ')}`).toEqual([]);
    }
  });
});

describe('coverage does not go backwards', () => {
  // Keys translated in SOME languages but not others — oversights, as opposed
  // to an English-only feature that is missing everywhere on purpose.
  //
  // Scoped to the RELEASED locales, which is the change that keeps it
  // meaningful. It used to measure all fourteen, on the assumption that they
  // advanced together. They do not any more: locales are shelved and finished
  // one at a time, so the moment Spanish reached 99.6% while thirteen shelved
  // catalogs sat at ~38%, nearly every key in the app became "partial" and the
  // count went from 55 to 2,369. That number described the release policy
  // rather than any defect.
  //
  // Between locales the app actually offers, a gap IS a defect — a user picks
  // Spanish and gets an English string. That is what this counts now.
  const RELEASED = JSON.parse(fs.readFileSync(path.join(DIR, '_meta.json'), 'utf8'))
    .released.locales.filter(l => l !== 'en');
  const CEILING = 55;

  it(`has no more than ${CEILING} partial gaps among released locales`, () => {
    const partial = [...en].filter(k => {
      const missing = RELEASED.filter(l => !keys[l].has(k)).length;
      return missing > 0 && missing < RELEASED.length;
    });
    expect(
      partial.length,
      `partial gaps went up. Run: node scripts/i18n-audit.mjs --partial`
    ).toBeLessThanOrEqual(CEILING);
  });

  // ── NO-REGRESSION GUARD ────────────────────────────────────────────────
  //
  // Replaces a 0.79 floor over a ratio, and the 431-line AWAITING_TRANSLATION
  // list that floor needed in order to stay meaningful.
  //
  // That list existed for a real reason, stated in its own header: the ratio
  // fell whenever `en` grew, so extracting a hardcoded English string INTO a
  // key read as a regression — penalising the one workflow that makes a
  // string translatable at all, and rewarding leaving copy hardcoded in JSX
  // where no audit can see it. Every exempt prefix was a hand-written apology
  // for that, carrying a justification comment and owing a later deletion.
  //
  // Counting the numerator alone removes the cause rather than the symptom.
  // `translated` is how many keys a locale defines; adding English copy
  // cannot move it, so extraction is free and the exemptions are unnecessary.
  // The numbers live in src/locales/_coverage.json and are regenerated with
  // `npm run i18n:baseline` — a deliberate act that shows up as a diff, which
  // is what the prefix list was reaching for.
  //
  // Two directions, because there are two ways to go backwards:
  //   translated  must not FALL — a locale losing copy it already had.
  //   englishEcho must not RISE — English pasted in as a placeholder and
  //                               counted as though it were a translation.
  const baseline = JSON.parse(fs.readFileSync(path.join(DIR, '_coverage.json'), 'utf8'));
  const dict = (l) => JSON.parse(fs.readFileSync(path.join(DIR, `${l}.json`), 'utf8'));
  const enDict = dict('en');
  const hasLetters = (v) => /\p{L}/u.test(String(v));

  // A COGNATE IS NOT A PLACEHOLDER, and this used to count them as one.
  // `echoCount` read the locale JSON flat and never consulted
  // ALLOW_IDENTICAL_BY_LANG — so "Cardio", "Level", "ml" and "{n}×" all
  // scored against German exactly as a pasted English sentence would.
  // The failure message even said "real cognates belong in
  // ALLOW_IDENTICAL_BY_LANG", which was advice that could not work:
  // adding them there changed nothing this test measured.
  //
  // The practical effect was backwards. Translating MORE of a locale
  // surfaces MORE cognates, so a push that took German 67% -> 90% made
  // this number rise and read as a regression — penalising the work it
  // exists to protect, which is the same trap the AWAITING_TRANSLATION
  // list fell into and that the block above was written to escape.
  //
  // Parsed from source rather than imported: i18n-check.js pulls in
  // ./i18n, which dynamic-imports every locale aggregate. The two tests
  // at the foot of this file already parse it the same way, and they are
  // what keeps the list honest (no non-Latin scripts, no stale entries).
  const checkSrc = fs.readFileSync(path.join('src/lib', 'i18n-check.js'), 'utf8');
  //
  // BOTH lists, and reading only the per-language one was a half-done fix.
  // `nav.hub`, `nutrition.water.ml` and `settings.weightUnit.kg` live in the
  // GLOBAL `ALLOW_IDENTICAL` — the file's own comment names "ml" as an example
  // of what should not score — and every one of them was still counted against
  // all fourteen locales. A key the repo has already declared identical on
  // purpose must not read as a missing translation, wherever it is declared.
  const globalIdentical = (() => {
    const m = checkSrc.match(/const ALLOW_IDENTICAL = new Set\(\[([\s\S]*?)\]\);/);
    return new Set(m ? [...m[1].matchAll(/'([\w.]+)'/g)].map((x) => x[1]) : []);
  })();
  const cognates = (l) => {
    const m = checkSrc.match(
      new RegExp(`^ {2}${l}: new Set\\(\\[([\\s\\S]*?)\\]\\),`, 'm'),
    );
    const own = m ? [...m[1].matchAll(/'([\w.]+)'/g)].map((x) => x[1]) : [];
    return new Set([...globalIdentical, ...own]);
  };

  const echoCount = (l) => {
    const d = dict(l);
    const ok = cognates(l);
    return Object.keys(d).filter(
      (k) => enDict[k] != null && d[k] === enDict[k] && hasLetters(enDict[k])
             && !ok.has(k),
    ).length;
  };

  it('every supported locale has a baseline entry', () => {
    // A locale with no entry is unguarded — silently, and forever.
    expect(Object.keys(baseline.locales).sort()).toEqual([...OTHERS].sort());
  });

  it.each(OTHERS)('%s has not lost translated keys', (lang) => {
    const now = keys[lang].size;
    const was = baseline.locales[lang].translated;
    expect(
      now,
      `${lang} fell from ${was} to ${now} translated keys. A locale losing copy ` +
      'it already had is a bug, not a baseline change. If the drop is intended ' +
      '(dead keys deleted, say), run `npm run i18n:baseline` and say why in the commit.',
    ).toBeGreaterThanOrEqual(was);
  });

  it.each(OTHERS)('%s has not gained English placeholders', (lang) => {
    const now = echoCount(lang);
    const was = baseline.locales[lang].englishEcho;
    expect(
      now,
      `${lang} went from ${was} to ${now} keys holding the English string verbatim. ` +
      'That is a key which exists and a translation which does not — invisible to ' +
      'any coverage count, and English on screen. Cognates are already excluded ' +
      'via ALLOW_IDENTICAL_BY_LANG in i18n-check.js, so add one there ONLY if the ' +
      'value is genuinely the same word in that language — otherwise translate it.',
    ).toBeLessThanOrEqual(was);
  });
});

describe('the two classes coverage cannot see', () => {
  // WHY THIS EXISTS. Every number above is measured against en.json. Both
  // failures below live OUTSIDE en.json, so they are absent from the
  // numerator and the denominator alike and no per-locale count can move
  // when one of them gets worse. That is not a rounding error: measured on
  // 2026-08-16 they were 764 + 724 = 1,488 user-visible strings against
  // 3,895 catalog keys, so real Spanish coverage was 70.5% while section B
  // reported 97.5% and _coverage.json had read 99.4%.
  //
  // Kegan reported it from a screenshot — "most titles are all english
  // still, and cards carasells" — while every guard in this file was green.
  // A number that can read 99.4% over a half-English dashboard is worse
  // than no number, because it is quoted.
  const baseline = JSON.parse(fs.readFileSync(path.join(DIR, '_coverage.json'), 'utf8'));

  it('does not gain untranslatable keys', () => {
    // tFallback('some.key', 'English') where some.key is in NO catalog,
    // en.json included. getTranslation resolves language -> en -> key, so
    // every language falls through to that English literal, permanently.
    // It is not a missing translation; it is a string a translator never
    // receives, because it is not in a file they are given.
    //
    // The fix is one line: add the key to en.json. Then it becomes an
    // ordinary gap that section B counts and a locale can close.
    const { bare, safe } = collectCallSites();
    const untranslatable = [...new Set([...safe, ...bare.keys()])]
      .filter((k) => !en.has(k) && safe.has(k));
    expect(
      untranslatable.length,
      `untranslatable keys rose from ${baseline.untranslatable} to ${untranslatable.length}. ` +
      'A new tFallback whose key is not in en.json renders English in all 15 ' +
      'languages forever. Add the key to src/locales/en.json in the same change. ' +
      'List them with: node scripts/i18n-audit.mjs --untranslatable',
    ).toBeLessThanOrEqual(baseline.untranslatable);
  });

  it('does not gain hardcoded strings', () => {
    // Strings that never reached a catalog at all — including copy held as
    // object-literal properties (`{ label: 'Log last night's sleep' }`),
    // which no JSX- or call-shaped detector could see. That blind spot is
    // why this scanner reported 1 TOTAL while questCatalog.js held 36 and
    // HeroSlideshow.jsx — the dashboard carousel Kegan was looking at — 43.
    const out = execFileSync('node', ['scripts/i18n-hardcoded.mjs', '--json'], {
      encoding: 'utf8', maxBuffer: 32 * 1024 * 1024,
    });
    const now = new Set(JSON.parse(out).map((f) => `${f.file}:${f.line}:${f.text}`)).size;
    expect(
      now,
      `hardcoded strings rose from ${baseline.hardcoded} to ${now}. ` +
      'Route the string through tFallback(key, \'English\') and add the key to ' +
      'en.json. See it with: npm run i18n:hardcoded -- --list',
    ).toBeLessThanOrEqual(baseline.hardcoded);
  });
});

describe('the brand name is never translated', () => {
  // kegan, 2026-08-16: "Keep Flexyn name and usernames Hardcoded."
  //
  // Usernames need no guard — they only ever travel as a {handle} / {name}
  // placeholder, and the batch validator already pins placeholder parity, so
  // a locale cannot drop or rename one. The brand is the part that can drift:
  // it sits INSIDE prose, where a translator (or a machine pass) can quietly
  // localise it while every other check stays green. "Flexyn" is in
  // _glossary.json's doNotTranslate.terms and app.name is in ALLOW_IDENTICAL,
  // but neither of those asserts it survives a sentence.
  const enDict = JSON.parse(fs.readFileSync(path.join(DIR, 'en.json'), 'utf8'));
  const branded = Object.keys(enDict).filter((k) => /Flexyn/.test(String(enDict[k])));

  it('has strings to check', () => {
    expect(branded.length).toBeGreaterThan(10);
  });

  it.each(OTHERS)('%s keeps Flexyn in every string that carries it', (lang) => {
    const d = JSON.parse(fs.readFileSync(path.join(DIR, `${lang}.json`), 'utf8'));
    const dropped = branded
      .filter((k) => d[k] != null && !/Flexyn/.test(String(d[k])))
      .map((k) => `${k}: ${d[k]}`);
    expect(
      dropped,
      `${lang} translated the brand name away. Flexyn stays verbatim in every ` +
      'language — it is a name, not a word.',
    ).toEqual([]);
  });
});

describe('a Latin-script locale stays in Latin script', () => {
  // A single Cyrillic character inside a Portuguese sentence is invisible to
  // every other guard here: the shape validator checks placeholders, newlines
  // and markdown; i18n-review checks vocabulary and register; the mojibake
  // scan looks for the Ã-shaped wreckage of UTF-8-through-latin-1. None of
  // them look at the SCRIPT of the letters.
  //
  // This was written after typing "Не foi possível" into pt.json — Cyrillic
  // Н-е instead of "Nã", from a keyboard slip. It renders as a real word to
  // nobody, and it survived a clean shape validation and a clean review.
  //
  // Scoped to the locales whose script is Latin, obviously. The six
  // non-Latin catalogs are excluded, and `en` is here because an English
  // string with a stray Cyrillic letter is the same bug.
  const LATIN = ['en', 'es', 'fr', 'de', 'pt', 'it', 'tr', 'pl', 'nl'];
  // Cyrillic and Greek blocks. Not an exhaustive "non-Latin" test — these are
  // the two that carry look-alike letters (а е о р с х, ο ρ) and so are the
  // two that produce a defect a reader's eye slides straight over.
  const CONFUSABLE = /[Ͱ-ϿЀ-ӿ]/;

  it.each(LATIN)('%s has no Cyrillic or Greek characters', (lang) => {
    const d = JSON.parse(fs.readFileSync(path.join(DIR, `${lang}.json`), 'utf8'));
    const bad = Object.entries(d)
      .filter(([, v]) => CONFUSABLE.test(String(v)))
      .map(([k, v]) => `${k}: ${v}`);
    expect(
      bad,
      `${lang} contains Cyrillic or Greek letters inside Latin-script copy. ` +
      'This is almost always a keyboard slip that no other guard can see — ' +
      'the shape validator, i18n-review and the mojibake scan all pass it.',
    ).toEqual([]);
  });
});

describe('no language may be aliased to the English object', () => {
  // THE bug of this whole cleanup, found eight times across nine files.
  // A part file that does `it: enKeys, ko: enKeys, …` reports 100% key
  // coverage to any presence-based audit while rendering pure English to
  // those users. notifications, formcoach, gauntlet, marketplace,
  // discovery, league, generator, coach and share all shipped this way.
  //
  // The shortcut is understandable — it makes a namespace "complete"
  // instantly — but it is indistinguishable from finished work unless
  // you compare VALUES, which is why it survived so long. This test
  // makes the shortcut fail loudly instead.
  //
  // If you genuinely want a language to fall back to English, delete the
  // key from that language entirely. getTranslation already resolves
  // `language -> en -> key`, so omission gives you the English fallback
  // AND stays visible to the audit as a real gap.
  it('no i18n part file maps a non-English locale to enKeys', () => {
    const dir = 'src/lib';
    const offenders = [];
    for (const f of fs.readdirSync(dir).filter(x => /^i18n-.*\.js$/.test(x))) {
      const src = fs.readFileSync(path.join(dir, f), 'utf8');
      const hits = src.match(/\b(es|fr|de|pt|it|ja|ko|zh|ar|hi|ru|tr|pl|nl)\s*:\s*enKeys\b/g);
      if (hits) offenders.push(`${f} (${hits.length}: ${hits.join(', ')})`);
    }
    expect(
      offenders,
      'A locale aliased to enKeys looks translated but renders English. ' +
      'Either translate it, or omit the keys so the fallback is visible.'
    ).toEqual([]);
  });
});

describe('the i18n-check allow-lists stay honest', () => {
  // src/lib/i18n-check.js suppresses "untranslated" warnings for two
  // reasons: universal codes/units, and per-language cognates. Both are
  // load-bearing — a checker that cries wolf gets ignored, and it was
  // emitting 366 warnings before these were populated.
  //
  // But an allow-list is also the easiest place to hide a real gap, so
  // these two tests bound it in both directions.
  const src = fs.readFileSync(path.join('src/lib', 'i18n-check.js'), 'utf8');
  const NON_LATIN = ['ja', 'ko', 'zh', 'ar', 'hi', 'ru'];

  const perLang = {};
  for (const m of src.matchAll(/^ {2}(es|fr|de|pt|it|tr|pl|nl|ja|ko|zh|ar|hi|ru): new Set\(\[([\s\S]*?)\]\),/gm)) {
    perLang[m[1]] = [...m[2].matchAll(/'([\w.]+)'/g)].map(x => x[1]);
  }

  it('never allow-lists a cognate for a non-Latin-script language', () => {
    // A Japanese, Korean, Chinese, Arabic, Hindi or Russian value that
    // equals the English one cannot be a coincidence — different script.
    // It is always an untranslated string, so it must always warn.
    const bad = NON_LATIN.filter(l => perLang[l]?.length);
    expect(
      bad,
      `cognate allow-list must not cover non-Latin scripts: ${bad.join(', ')}`
    ).toEqual([]);
  });

  it('has no stale entries — every allow-listed cognate is still identical', () => {
    // If a key gets translated later, its allow-list entry becomes dead
    // weight that would silently suppress a future regression.
    const stale = [];
    for (const [lang, keys] of Object.entries(perLang)) {
      const dict = JSON.parse(fs.readFileSync(path.join(DIR, `${lang}.json`), 'utf8'));
      const enDict = JSON.parse(fs.readFileSync(path.join(DIR, 'en.json'), 'utf8'));
      for (const k of keys) {
        if (dict[k] !== undefined && enDict[k] !== undefined && dict[k] !== enDict[k]) {
          stale.push(`${lang}:${k}`);
        }
      }
    }
    expect(stale, `remove these from ALLOW_IDENTICAL_BY_LANG: ${stale.join(', ')}`).toEqual([]);
  });
});
